### PR TITLE
Add missing hooks actionCustomerLogout & displayCheckoutSummaryTop

### PR DESCRIPTION
**Pull request by okom3pom**
| Questions         | Answers
| ----------------- | -------------------------------------------------------
| Description?      | Add missing hooks actionCustomerLogout After Before and displayCheckoutSummaryTop
| Type?             | bug fix
| Category?         | IN
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/19894 AND https://github.com/PrestaShop/PrestaShop/issues/15594
| How to test?      | Install a new shop and made an upgrade to 8.0.0 after check the hook
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

---
This change is [Reviewable](https://reviewable.io/reviews/prestashop/prestashop/26072)

### CODE REVIEW

**Review by PierreRambaud — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by okom3pom** [comment]
Hello @marwachelly i rebase my PR

Regards

**Review by Progi1984 — DISMISSED** [review]

**Review by matks — DISMISSED** [review]

**Comment by boubkerbribri** [comment]
Hello @okom3pom 
Could you please fix CI before we test it ?

**Comment by okom3pom** [comment]
Hi @boubkerbribri, 

I will try again to restart the CI but all time the CI is bad. @Progi1984 @matks can you confirm it's not the PR

**Comment by marwachelly** [comment]
Hello, 

PR should be tested with an upgrede to 8.0.0. So it is blocked by the issue https://github.com/PrestaShop/PrestaShop/issues/26503.
It will be tested as soon as the issue will be resolved.

Thanks,

**Comment by Progi1984** [comment]
@PrestaShop/qa-functional I unlock this PR to QA as #26503 is fixed.

**Review by kpodemski — APPROVED** [review]

**Review by marwachelly — APPROVED** [review]
Hello,

Upgrade is succeful now and hooks displayCheckoutSummaryTop, actionCustomerLogoutBefore and actionCustomerLogoutAfter exist in the database.
image
https://watch.screencastify.com/v/fXKABfxxGEd0J3Cbq7Ej

Thanks,

**Comment by Progi1984** [comment]
Thanks @okom3pom & @marwachelly

**Pull request merged**
