### PR TITLE
New hook for performing actions when address change on cart

### PR DESCRIPTION
**Pull request by Prestaworks**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Added new hook from PR 31294 to autoupgrade script
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| Sponsor company   | Prestaworks AB
| Related PRs | https://github.com/PrestaShop/PrestaShop/pull/31294

### CODE REVIEW

**Review by matthieu-rolland — APPROVED** [review]
LGTM

But this PR should not be merged before https://github.com/PrestaShop/PrestaShop/pull/31294 is merged

**Comment by hibatallahAouadni** [comment]
Hello @Prestaworks 

Could you please resolve the conflits 🙏 
Ping @kpodemski as discussed on Slack, this PR should be tested by a dev.

Thanks!

**Comment by Prestaworks** [comment]
> Hello @Prestaworks
> 
> Could you please resolve the conflits 🙏 Ping @kpodemski as discussed on Slack, this PR should be tested by a dev.
> 
> Thanks!

Done!

**Review by florine2623 — COMMENTED** [review]
Hello @Prestaworks ,

Thanks for the PR.

I have an exception when I try to test your PR :
Screenshot 2023-03-15 at 17 31 56

Maybe it needs a rebase :
Screenshot 2023-03-15 at 17 35 56

Could you check ?
Thanks!

**Comment by Hlavtox** [comment]
@florine2623 You did not run composer install

**Comment by Prestaworks** [comment]
Not sure if I need to do anything else here? waiting for QA was removed and florine seems to have removed her assignment?

**Comment by kpodemski** [comment]
@Prestaworks sorry for that, no worries, nothing more to do on your side, we'll handle that

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
thank you @Prestaworks :)

**Pull request merged**
