### PR TITLE
Add index to `PREFIX_orders.invoice_date`

### PR DESCRIPTION
**Pull request by AdrienPlx**
Related to pull request https://github.com/PrestaShop/PrestaShop/pull/31218. Improve back office performances on Categories lisiting

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Add index to `PREFIX_orders.invoice_date` to increase performances on AdminStatsController ajax function to get best category on KPIs listing of categories in BO (huge timing on big shops)
| Type?             | improvement
| How to test?      | Go to categories listing page in BO and analyse network timing on this request : index.php?controller=AdminStats&ajax=1&action=getKpi&kpi=top_category. It will be significant if you have a shop with a lot of categories, orders and products. Add the index on ps_orders.'invoice_date' and see the difference

### CODE REVIEW

**Comment by Hlavtox** [comment]
@AdrienPlx Bro can you add the two SESSION and NAMES commands to the top like here? https://github.com/AdrienPlx/autoupgrade/blob/patch-1/upgrade/sql/8.1.0.sql

Not sure if its needed, but just to be safe. 👍

**Comment by AdrienPlx** [comment]
> @AdrienPlx Bro can you add the two SESSION and NAMES commands to the top like here? https://github.com/AdrienPlx/autoupgrade/blob/patch-1/upgrade/sql/8.1.0.sql
> 
> Not sure if its needed, but just to be safe. 👍

Hi, this is done !

**Review by Hlavtox — APPROVED** [review]

**Comment by kpodemski** [comment]
hey @AdrienPlx 

Your PR to the core has been merged 🎉 do you think you could resolve conflicts in this PR? There were some others in the meantime.

**Comment by Hlavtox** [comment]
Bump @AdrienPlx

**Comment by AdrienPlx** [comment]
I think it's ok ! @Hlavtox

**Review by Hlavtox — APPROVED** [review]

**Comment by Hlavtox** [comment]
Tested, works properly.

**Pull request merged**
