### PR TITLE
Change the APE field validation to match all formats

### PR DESCRIPTION
**Pull request by alexandrebak42**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      |  This PR is linked to PR [34242](https://github.com/PrestaShop/PrestaShop/pull/34242). It just update the PREFIX_customer.ape field from varchar(5) to varchar(6) to match all french APE code formats. I hope I haven't forgotten anything.
| Type?             |  improvement 
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes for PR [34242](https://github.com/PrestaShop/PrestaShop/pull/34242), Fixes for issue [34216](https://github.com/PrestaShop/PrestaShop/discussions/34216)
| Sponsor company   | coquille.fr
| How to test?      | The ape field in  PREFIX_customer table should be varchar(6) after upgrade.

### CODE REVIEW

**Review by boherm — CHANGES_REQUESTED** [review]
Hello @alexandrebak42! Thanks for your contribution.
As you target `develop` branch (and so the 9.0.0 version of PrestaShop) in your https://github.com/PrestaShop/PrestaShop/pull/34217, you have to edit the `sql/9.0.0.sql` file instead of `8.1.3.sql`.

**Comment by alexandrebak42** [comment]
Oh ok sorry, this is my first PR on an open-source repository ! If I wanted the changes to take effect on 8.1.3 I should have done my PR on 8.1.X ?

**Comment by boherm** [comment]
> Oh ok sorry, this is my first PR on an open-source repository !
No problem! 😉

> If I wanted the changes to take effect on 8.1.3 I should have done my PR on 8.1.X ?
Yes, your PR must target the `8.1.x` branch in that case. 
By the way, it's preferable in your case I think 🤔

**Comment by alexandrebak42** [comment]
> Yes, your PR must target the `8.1.x` branch in that case. By the way, it's preferable in your case I think 🤔 And in that case, this PR is good!

Nice, I created a new PR on 8.1.x [here](https://github.com/PrestaShop/PrestaShop/pull/34242)

**Review by mflasquin — APPROVED** [review]

**Review by M0rgan01 — APPROVED** [review]

**Comment by M0rgan01** [comment]
Tests UI: https://github.com/M0rgan01/ga.tests.ui.pr/actions/runs/6627758782

**Comment by Hlavtox** [comment]
@alexandrebak42 Good job, works as it should. :-)

BEFORE
⏬ 
AFTER

**Pull request merged**
