### PR TITLE
Update new and obsolete hooks for 9.0.0

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Update new and obsolete hooks for 9.0.0
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | ~
| Sponsor company   | ~
| How to test?      | ~

This PR was auto-generated thanks to the core Symfony command, which was improved in this PR https://github.com/PrestaShop/PrestaShop/pull/37168

### CODE REVIEW

**Review by Quetzacoalt91 — DISMISSED** [review]

**Review by Hlavtox — CHANGES_REQUESTED** [review]
The query is missing ``ON DUPLICATE KEY UPDATE `title` = VALUES(`title`), `description` = VALUES(`description`);``

(This was added by my PR to update automatically-added hooks that would now be without description.)

**Comment by jolelievre** [comment]
@Hlavtox you're right I integrated it in the command later, but I must have updated this PR improperly

**Comment by jolelievre** [comment]
@Hlavtox @Quetzacoalt91 this should be good now

**Review by Hlavtox — DISMISSED** [review]
Thanks @jolelievre 👍

**Comment by Quetzacoalt91** [comment]
Incoming conflict with https://github.com/PrestaShop/autoupgrade/pull/981

**Comment by jolelievre** [comment]
Thanks @Quetzacoalt91 it's fixed, it would be great if this one can be validated soon to avoid any other conflicts because it is blocking the core PR that generates this automatically https://github.com/PrestaShop/PrestaShop/pull/37168

Once the new command is merged we'll update the release process so that it is included in the steps to do by the core team, this means people won't need to create update hooks PR because we can semi-automatically handle all of them as long as the `hook.xml` file has been correctly updated in the core.

One possible improvement of the CLI command would be to update an already existing SQL query for hooks, but this will be done in some other PR if needed.

**Review by Quetzacoalt91 — APPROVED** [review]

**Review by AureRita — APPROVED** [review]
Hi @jolelievre 

Thank you for your PR, I tested it and it seems to works. 

Tested from : 
8.0.4 to 8.2  
8.2 to 9.0.0
8.0.4 to 9.0.0

Because the PR seems to works as expected, It's QA :heavy_check_mark: 

Thank you

**Pull request merged**
