### PR TITLE
Bump version number to 5.0.0

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Bump version number to 5.0.0. This new version must be a new major version because it contains breaking changes: for example the change of minimum PrestaShop version (1.7 instead of 1.6) and the removal the migration scripts for versions lower than 1.7
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     |
| Fixed ticket?     | 
| Sponsor company   | 
| How to test?      | No need to test

### CODE REVIEW

**Review by Hlavtox — DISMISSED** [review]
@matks I think you accidentaly renamed the upgrade file. :-)

**Comment by matks** [comment]
> @matks I think you accidentaly renamed the upgrade file. :-)

This was on purpose but indeed a mistake. I wanted to rename everything 4.16.5 to 5.0.0 but I renamed 8.1.3 in 5.0.0

**Comment by matks** [comment]
Fixed

**Review by jolelievre — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by matks** [comment]
Merged, @AureRita said no need for QA 😉

**Pull request merged**
