### PR TITLE
Move controller in proper folder to make it accessible on PS v9

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Fixes the loading of the upgrade module on PrestaShop v9
| Type?             | bug fix
| BC breaks?        | Nope
| Deprecations?     | Nope
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/35540
| How to test?      | Open the configuration page of the module `autoupgrade`. The module should be accessible as on PS v8 and below.

image

### CODE REVIEW

**Review by Hlavtox — APPROVED** [review]

**Review by SharakPL — APPROVED** [review]

**Review by boherm — APPROVED** [review]

**Comment by AureRita** [comment]
Hi @Quetzacoalt91 

Thank you for your PR, I tested you PR but currently I've this type of behavior : 

[recording(143).webm](https://github.com/PrestaShop/autoupgrade/assets/100699445/4a9f4c45-d382-4522-b043-5cdc08e41489)

We can now access to the BO without syntax error, but we don't have the correct display of the 1-Click Upgrade. 
Moreover, we can see that we have an invalid token. It appears always when we want to configure the module. 

Waiting for your correction

**Comment by Quetzacoalt91** [comment]
Indeed, pulling the latest `develop` brought the additional issues you found

**Comment by Quetzacoalt91** [comment]
Isn't @ps-jarvis supposed to remove the "Waiting for author" label when the branch is updated?

**Review by Hlavtox — APPROVED** [review]

**Comment by Hlavtox** [comment]
@Quetzacoalt91 The bots are broken... :-)

@AureRita You can re-test 👍

**Review by AureRita — APPROVED** [review]

**Comment by Hlavtox** [comment]
@AureRita @Quetzacoalt91 The tab should be there guys, it's an issue if it's not. 🤔

**Comment by AureRita** [comment]
in my opinion, yes, because it was here on all the previous version but we can take this issue on other PR.

**Comment by Quetzacoalt91** [comment]
It depends if the issue happens on all versions because of this PR or only if the v9 is only impacted.

If all versions are concerned, I'll be happy to fix this in this PR.

**Comment by MatShir** [comment]
On v5.0.1 and PS 8.1.3, the upgrade is well displayed in the menu. It may be a regression from 5.0.2

**Comment by AureRita** [comment]
With your PR and 8.1.x, we have the autoupgrade on the side bar. 

Because this issue is not related to this PR, I think we can merge it :rocket:

**Pull request merged**
