### PR TITLE
Add a display hook in the address step

### PR DESCRIPTION
**Pull request by Amit-Kumar-Tiwari-Webkul**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | There is no possibility to add something (message) on address step of checkout. So we suggest please add a display hook in the address step also just like other checkout steps.
| Type?             |  new feature 
| BC breaks?        | no
| Deprecations?     |  no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/30666
| How to test?      | Please indicate how to best verify that this PR is correct.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Comment by Hlavtox** [comment]
@florine2623 You don't need to QA it until https://github.com/PrestaShop/autoupgrade/pull/539 is merged, it won't work.

**Comment by florine2623** [comment]
Waiting for PM approval before testing it.

https://github.com/PrestaShop/PrestaShop/issues/30666#issuecomment-1365902193

**Comment by MatShir** [comment]
LGTM ✅, you can test it @florine2623.
Don't hesitate to ping at https://github.com/orgs/PrestaShop/teams/product-team and on slack #project-member so we can quickly reply ;)

**Review by SharakPL — APPROVED** [review]

**Review by MhiriFaten — COMMENTED** [review]
Hello @Amit-Kumar-Tiwari-Webkul ,

We have already an issue when upgrading to develop.

image

So, this PR should be tested when the issue will be fixed.
I'll add the Blocked label for that.

Thanks.

**Comment by MatShir** [comment]
Hi @MhiriFaten, could you make an issue with the steps ? :)
The team will take a look at it ;)

**Comment by MhiriFaten** [comment]
@MatShir 
We have already experienced the same problem.
https://github.com/PrestaShop/autoupgrade/pull/534#pullrequestreview-1229015988
https://github.com/PrestaShop/autoupgrade/pull/535#pullrequestreview-1220648158
https://github.com/PrestaShop/autoupgrade/pull/539#pullrequestreview-1224283391

and as is also discussed in the slack channel not to make an issue, that's why we didn't create it.

So, we create the issue?

**Comment by MatShir** [comment]
On slack, we talk that for the release of the version 4.15 we shouldn't test an upgrade for 'develop' because it was out of the scope. 
Here the PRs are scoped for the 'develop' and block many tests then we should create an issue for each problem faced, so we can fix them :)

**Comment by Hlavtox** [comment]
@MatShir Bro, just wait until https://github.com/PrestaShop/autoupgrade/pull/539 is finished, then all prs will work.

**Comment by Hlavtox** [comment]
Unblocked, PR may need a rebase to work.

**Review by MhiriFaten — COMMENTED** [review]
Hello @Amit-Kumar-Tiwari-Webkul ,

I have checked the autoupgrade with **`PS1788`** to **`8.1.0`** using the quality assurance module [ps_qualityassurance.zip](https://github.com/PrestaShop/PrestaShop/files/10307712/ps_qualityassurance.zip), and I used these codes in **`displayAddressSelectorBottom`**

> dump($params);
> die;
 

> return 'display hook testing';


But the adding of the display hook in the address step is not fixed. 


Here is a screen record
[Untitled_ Jan 17 2023 4_47 PM.webm](https://user-images.githubusercontent.com/111756615/212944972-a3172fb4-5639-4793-bfaa-cb5e6446a3a9.webm)

could you check it please ?

**Comment by Hlavtox** [comment]
@MhiriFaten This depends on a template.

The important thing is, that after you upgrade, do running this return the hook or not? :-) `SELECT * FROM ps_hook WHERE name='displayAddressSelectorBottom';`

**Review by MhiriFaten — COMMENTED** [review]
Hello @Amit-Kumar-Tiwari-Webkul ,

I have rechecked it with **PS1778** and **PS1788**,

I have added the classic theme, and I noticed that when I launched the display hook in the address step, there is a **`save`** button that appeared for split second and disappeared
and the hook name is not displayed in the hook address

**displayAddressSelectorBottom
Content**

> return 'heelooooo !!!';


**upgrade `1788` to `8.1.0`**

[Untitled_ Jan 18, 2023 11_54 AM.webm](https://user-images.githubusercontent.com/111756615/213154876-1df66a40-2600-42f5-812b-2b0954702f04.webm)

image


**upgrade `1778` to `8.1.0`**

[Untitled_ Jan 18, 2023 11_56 AM.webm](https://user-images.githubusercontent.com/111756615/213154691-48d01f9c-304e-4d4c-86e3-973f07f34386.webm)


image

Could you check it please ?

**Comment by kpodemski** [comment]
Hello @MhiriFaten 

If you have the hook in the database then it's ok. The rest was already tested with the usage of PRs from the `classic-theme`, etc. :)

**Pull request merged**
