### PR TITLE
Fixed bad parameter when updating configuration

### PR DESCRIPTION
**Pull request by M0rgan01**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Fixed bad parameter when updating configuration
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     |  no
| Fixed ticket?     | -
| Sponsor company   | -
| How to test?      | -

### CODE REVIEW

**Review by Quetzacoalt91 — DISMISSED** [review]

**Review by AureRita — APPROVED** [review]
Hi @M0rgan01 

Thank you for your PR, I tested it and it seems to works as you can see : 

[recording(271).webm](https://github.com/user-attachments/assets/aaa0ebe6-90e0-4198-815b-bfd6755511a0)


Tested from : 
1.7.8.10 to 8.1.7 
8.0.5 to 8.1.7  
8.1.7 to 9.0.0
8.1.5 to 9.0.0

Because the PR seems to works as expected, It's QA :heavy_check_mark: 

Thank you

**Review by Quetzacoalt91 — DISMISSED** [review]

**Comment by M0rgan01** [comment]
Blocked by https://github.com/PrestaShop/autoupgrade/pull/856

**Comment by M0rgan01** [comment]
@jolelievre the upgrade to v9 no longer worked following these pull requests. https://github.com/PrestaShop/PrestaShop/pull/36718 https://github.com/PrestaShop/PrestaShop/pull/36706

**Review by Quetzacoalt91 — APPROVED** [review]

**Review by AureRita — APPROVED** [review]
Hi @M0rgan01 

Thank you for your PR, I tested it and it seems to works as expected.

Tested from : 
1.7.8.10 to 8.1.7 
8.0.5 to 8.1.7 
8.1.7 to 9.0.0
8.1.5 to 9.0.0
8.0.5 to 9.0.0

Because the PR seems to works as expected, It's QA :heavy_check_mark: 

Thank you

**Pull request merged**
