### PR TITLE
Add config and data for discontinuted products

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Autoupgrade PR for https://github.com/PrestaShop/PrestaShop/pull/29720
| Type?             | new feature
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/pull/29720
| How to test?      | -
| Possible impacts? | -

### How to test
- Install Prestashop 8
- Check that some or all products have `redirect_type` in `ps_product` table `404`.
- Do upgrade to 8.1.
- Go check `ps_product` again and see that these products changed `redirect_type` to `default`.

### CODE REVIEW

**Review by kpodemski — APPROVED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @Hlavtox ,

I have tested the following:
- install PR 29720 on develop
- create a release of it
- install a 1.7.8.8 shop
- install module autoupgrade with PR 538
- upgrade the shop with the release created earlier

I have an error during the upgrade:
Screenshot 2022-12-14 at 10 57 57

The BO is not accessible, it has error 500. The FO is displayed but broken.

https://user-images.githubusercontent.com/16019289/207565563-af79e4cf-61ba-47b6-ab3c-c64449f839f6.mov

Is there something I am missing? ^^
Thanks!

**Comment by Hlavtox** [comment]
@florine2623 You need to enable debug mode in `config/defines.inc` so we can see what happens in BO. 

99 % sure it's not an issue with my PR. 👍

**Comment by Hlavtox** [comment]
@florine2623 Hi, you can test the upgrade v8 to v8.1, everything is ready. I added some "How to test" steps to PR description so you know what to look for. :-)

**Comment by hibatallahAouadni** [comment]
@Hlavtox we need a maintainer approval 😁

**Review by kpodemski — DISMISSED** [review]

**Comment by paulnoelcholot** [comment]
Hello @Hlavtox,

I have tried to install this PR but the installation crashes as you can see : 
image

I think the conflicts need to be resolved before we can test the PR

**Comment by Hlavtox** [comment]
I will rebase immediately after https://github.com/PrestaShop/autoupgrade/pull/534 is merged

**Review by jolelievre — DISMISSED** [review]

**Comment by hibatallahAouadni** [comment]
Blocked by #534

**Comment by Hlavtox** [comment]
@hibatallahAouadni @paulnoelcholot Ready to retest 👍

**Review by kpodemski — APPROVED** [review]

**Comment by paulnoelcholot** [comment]
Hello @Hlavtox,

I have tested your PR and it's finally OK for me :tada: 

Thanks!

**Review by paulnoelcholot — APPROVED** [review]

**Comment by Hlavtox** [comment]
Thank you @paulnoelcholot! 🍺🎉

**Pull request merged**
