### PR TITLE
Update mochawesome and fix nightly import

### PR DESCRIPTION
**Pull request by boubkerbribri**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Update mochawesome and fix nightly import (waiting for https://github.com/PrestaShop/QANightlyResults/pull/57 )
| Type?             | refacto
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | no
| How to test?      | to test on nightly
| Possible impacts? | none

### CODE REVIEW

**Comment by boubkerbribri** [comment]
PLEASE DO NOT MERGE THIS FOR NOW :stop_sign:

**Comment by matks** [comment]
> PLEASE DO NOT MERGE THIS FOR NOW 🛑

WHY DID YOU SAY THIS NOW I WANT TO MERGE THIS SO MUCH

**Review by PierreRambaud — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by NeOMakinG — APPROVED** [review]

**Comment by Progi1984** [comment]
@boubkerbribri Can we merge it NOW ?

**Comment by boubkerbribri** [comment]
> @boubkerbribri Can we merge it NOW ?

Yes, we can merge it.
Thanks

**Comment by Progi1984** [comment]
Thanks @boubkerbribri

**Pull request merged**
