### PR TITLE
Drop server performance configuration

### PR DESCRIPTION
**Pull request by M0rgan01**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Drop server performance configuration
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | -
| Sponsor company   | -
| How to test?      | -

### CODE REVIEW

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by kpodemski** [comment]
Are you planning to allow developers to override these values? Time is precious.

**Comment by M0rgan01** [comment]
@kpodemski According to our metrics this configuration was very little modified. We aim to simplify the update process so that users are as comfortable as possible.

Time is precious -> We also study the subject of performance :)

**Comment by kpodemski** [comment]
@M0rgan01 

> According to our metrics this configuration was very little modified. We aim to simplify the update process so that users are as comfortable as possible.

Of course, and that's a good approach. Two thoughts:
- nontechnical users probably won't end up doing major upgrades,
- it is an agency or technical person who does the upgrade quite often - I don't want to modify the module's files to make things quicker because I run on `max_execution=-1` and `memory_limit=-1`, etc., so it would be great to have it configurable, even by having a code like this:

$nbFiles = Configuration::get('PS_AUTOUPGRADE_NB_FILES, null, null, null, 400);

so I could tinker with perf settings :D

**Comment by Hlavtox** [comment]
I don't think the loop size/time is to concern, if the upgrade takes 2 minutes o 2 minutes 5 seconds is irrelevant.

What is concerning is `'maxBackupFileSize' => [15728640, 31457280, 62914560], // bytes`, this changes the behavior of the backup. Not that I ever used this. :-)))

**Review by AureRita — APPROVED** [review]
Hi @M0rgan01 

Thank you for your PR, I tested it and it seems to works as you can see : 

[recording(287).webm](https://github.com/user-attachments/assets/1117cadf-947c-4ffd-a2bf-a4f20293a95c)


Tested from : 
1.7.8.9 to 8.1.7 
8.0.5 to 8.1.7 
8.1.7 to 9.0.0
8.1.5 to 9.0.0
8.0.5 to 9.0.0

Because the PR seems to works as expected, It's QA :heavy_check_mark: 

Thank you

**Pull request merged**
