### PR TITLE
Move upgrade scripts from the Core to the autoupgrade module

### PR DESCRIPTION
**Pull request by PierreRambaud**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Do not use Upgrade Core files when using this module. Move part related to PS_ADMIN_DIR inside the Admin controller to be sure we are still able to install this module at the installation of a new PrestaShop.
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes PrestaShop/PrestaShop#23240
| How to test?      | Try to upgrade everything :tada: .
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

### CODE REVIEW

**Review by atomiix — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by sarahdib** [comment]
@PierreRambaud 

Two upgrades failed with this pr. FO is broken but good news the restoration process is working :p 
- 1.6.1.24 -> 1.7.7.5 
`[ERROR] 1.7.0.0 PHP - missing file /* PHP:select_current_payment_modules(); */[ERROR] 1.7.0.0 PHP - missing file /* Add Payment Preferences tab. SuperAdmin profile is the only one to access it. */ /* PHP:ps_1700_add_payment_preferences_tab(); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:ps1700_stores(); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:ps_1700_add_locale(); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:add_quick_access_tab(); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(displayProductTab); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(displayProductTabContent); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(displayBeforePayment); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(actionBeforeAuthentication); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(actionOrderDetail); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(actionProductListOverride); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(actionSearch); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(displayCustomerIdentityForm); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(displayHomeTab); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(displayHomeTabContent); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(displayPayment); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(displayProductComparison); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:migrate_tabs_17(); */[ERROR] 1.7.0.0 PHP - missing file /* Properly migrate the rights associated with each tabs */ /* PHP:ps_1700_right_management(); */[ERROR] 1.7.0.5 PHP - missing file /* PHP:ps_update_tabs(); */[ERROR] 1.7.2.0 PHP - missing file /* PHP:drop_column_from_product_lang_if_exists(); */[ERROR] 1.7.2.0 PHP - missing file /* PHP:add_new_status_stock(); */[ERROR] 1.7.3.0 PHP - missing file /* PHP:ps_1730_add_quick_access_evaluation_catalog(); */[ERROR] 1.7.3.0 PHP - missing file /* PHP:ps_1730_move_some_aeuc_configuration_to_core(); */[ERROR] 1.7.3.0 PHP - missing file /* PHP:ps_1730_migrate_data_from_store_to_store_lang_and_clean_store(); */[ERROR] 1.7.4.0 PHP - missing file /* PHP:ps_1740_update_module_tabs(); */[ERROR] 1.7.5.0 PHP - missing file /* PHP:add_supplier_manufacturer_routes(); */[ERROR] 1.7.5.0 PHP - missing file /* PHP:ps_1750_update_module_tabs(); */[ERROR] 1.7.5.1 PHP - missing file /* PHP:ps_1751_update_module_sf_tab(); */[ERROR] 1.7.6.0 PHP - missing file /* PHP:ps_1760_copy_data_from_currency_to_currency_lang(); */[ERROR] 1.7.6.0 PHP - missing file /* PHP:ps_1760_update_configuration(); */[ERROR] 1.7.6.0 PHP - missing file /* PHP:ps_1760_update_tabs(); */[ERROR] 1.7.6.1 PHP - missing file /* PHP:ps_1761_update_currencies(); */SQL 1.7.6.2 1136 in INSERT INTO `ps_product_lang` SELECT `entity`.`id_product`, 1, `entity`.`id_lang`, `entity`.`description`, `entity`.`description_short`, `entity`.`link_rewrite`, `entity`.`meta_description`, `entity`.`meta_keywords`, `entity`.`meta_title`, `entity`.`name`, `entity`.`available_now`, `entity`.`available_later`, `entity`.`delivery_in_stock`, `entity`.`delivery_out_stock` FROM `ps_product_lang` entity LEFT JOIN `ps_product_lang` entity2 ON `entity2`.`id_shop` = 1 AND `entity`.`id_product` = `entity2`.`id_product` WHERE `entity2`.`id_shop` IS NULL: Column count doesn't match value count at row 1[ERROR] 1.7.6.3 PHP - missing file /* PHP:ps_1763_update_tabs(); */[ERROR] 1.7.7.0 PHP - missing file /* PHP:ps_1770_preset_tab_enabled(); */[ERROR] 1.7.7.0 PHP - missing file /* PHP:ps_1770_update_order_status_colors(); */[ERROR] 1.7.7.1 PHP - missing file /* PHP:ps_1771_update_customer_note(); */[INTERNAL] /Users/sDib/www/PrestaShop/presta_16124/src/Core/Addon/Module/ModuleManager.php line 280 - Exception: You are not allowed to install modules. #0 /Users/sDib/www/PrestaShop/presta_16124/src/Core/Addon/Theme/ThemeManager.php(345): PrestaShop\PrestaShop\Core\Addon\Module\ModuleManager->install('ps_linklist') #1 /Users/sDib/www/PrestaShop/presta_16124/src/Core/Addon/Theme/ThemeManager.php(226): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeManager->doEnableModules(Array) #2 /Users/sDib/www/PrestaShop/presta_16124/modules/autoupgrade/classes/UpgradeTools/ThemeAdapter.php(92): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeManager->enable('classic') #3 /Users/sDib/www/PrestaShop/presta_16124/modules/autoupgrade/classes/UpgradeTools/ThemeAdapter.php(51): PrestaShop\Module\AutoUpgrade\UpgradeTools\ThemeAdapter->enableTheme17('classic') #4 /Users/sDib/www/PrestaShop/presta_16124/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(681): PrestaShop\Module\AutoUpgrade\UpgradeTools\ThemeAdapter->enableTheme('classic') #5 /Users/sDib/www/PrestaShop/presta_16124/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(118): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->updateTheme() #6 /Users/sDib/www/PrestaShop/presta_16124/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #7 /Users/sDib/www/PrestaShop/presta_16124/admin-dev/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #8 {main}`

- 1.7.5.2 -> 1.7.7.5
`[ERROR] 1.7.6.0 PHP - missing file /* PHP:ps_1760_copy_data_from_currency_to_currency_lang(); */[ERROR] 1.7.6.0 PHP - missing file /* PHP:ps_1760_update_configuration(); */[ERROR] 1.7.6.0 PHP - missing file /* PHP:ps_1760_update_tabs(); */[ERROR] 1.7.6.1 PHP - missing file /* PHP:ps_1761_update_currencies(); */[ERROR] 1.7.6.3 PHP - missing file /* PHP:ps_1763_update_tabs(); */[ERROR] 1.7.7.0 PHP - missing file /* PHP:ps_1770_preset_tab_enabled(); */[ERROR] 1.7.7.0 PHP - missing file /* PHP:ps_1770_update_order_status_colors(); */[ERROR] 1.7.7.1 PHP - missing file /* PHP:ps_1771_update_customer_note(); */`

**Comment by PierreRambaud** [comment]
> @PierreRambaud
> 
> Two upgrades failed with this pr. FO is broken but good news the restoration process is working :p
> 
> * 1.6.1.24 -> 1.7.7.5
>   `[ERROR] 1.7.0.0 PHP - missing file /* PHP:select_current_payment_modules(); */[ERROR] 1.7.0.0 PHP - missing file /* Add Payment Preferences tab. SuperAdmin profile is the only one to access it. */ /* PHP:ps_1700_add_payment_preferences_tab(); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:ps1700_stores(); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:ps_1700_add_locale(); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:add_quick_access_tab(); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(displayProductTab); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(displayProductTabContent); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(displayBeforePayment); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(actionBeforeAuthentication); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(actionOrderDetail); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(actionProductListOverride); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(actionSearch); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(displayCustomerIdentityForm); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(displayHomeTab); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(displayHomeTabContent); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(displayPayment); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(displayProductComparison); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:migrate_tabs_17(); */[ERROR] 1.7.0.0 PHP - missing file /* Properly migrate the rights associated with each tabs */ /* PHP:ps_1700_right_management(); */[ERROR] 1.7.0.5 PHP - missing file /* PHP:ps_update_tabs(); */[ERROR] 1.7.2.0 PHP - missing file /* PHP:drop_column_from_product_lang_if_exists(); */[ERROR] 1.7.2.0 PHP - missing file /* PHP:add_new_status_stock(); */[ERROR] 1.7.3.0 PHP - missing file /* PHP:ps_1730_add_quick_access_evaluation_catalog(); */[ERROR] 1.7.3.0 PHP - missing file /* PHP:ps_1730_move_some_aeuc_configuration_to_core(); */[ERROR] 1.7.3.0 PHP - missing file /* PHP:ps_1730_migrate_data_from_store_to_store_lang_and_clean_store(); */[ERROR] 1.7.4.0 PHP - missing file /* PHP:ps_1740_update_module_tabs(); */[ERROR] 1.7.5.0 PHP - missing file /* PHP:add_supplier_manufacturer_routes(); */[ERROR] 1.7.5.0 PHP - missing file /* PHP:ps_1750_update_module_tabs(); */[ERROR] 1.7.5.1 PHP - missing file /* PHP:ps_1751_update_module_sf_tab(); */[ERROR] 1.7.6.0 PHP - missing file /* PHP:ps_1760_copy_data_from_currency_to_currency_lang(); */[ERROR] 1.7.6.0 PHP - missing file /* PHP:ps_1760_update_configuration(); */[ERROR] 1.7.6.0 PHP - missing file /* PHP:ps_1760_update_tabs(); */[ERROR] 1.7.6.1 PHP - missing file /* PHP:ps_1761_update_currencies(); */SQL 1.7.6.2 1136 in INSERT INTO `ps_product_lang`SELECT`entity`.`id_product`, 1, `entity`.`id_lang`, `entity`.`description`, `entity`.`description_short`, `entity`.`link_rewrite`, `entity`.`meta_description`, `entity`.`meta_keywords`, `entity`.`meta_title`, `entity`.`name`, `entity`.`available_now`, `entity`.`available_later`, `entity`.`delivery_in_stock`, `entity`.`delivery_out_stock`FROM`ps_product_lang`entity LEFT JOIN`ps_product_lang`entity2 ON`entity2`.`id_shop`= 1 AND`entity`.`id_product`=`entity2`.`id_product`WHERE`entity2`.`id_shop` IS NULL: Column count doesn't match value count at row 1[ERROR] 1.7.6.3 PHP - missing file /* PHP:ps_1763_update_tabs(); */[ERROR] 1.7.7.0 PHP - missing file /* PHP:ps_1770_preset_tab_enabled(); */[ERROR] 1.7.7.0 PHP - missing file /* PHP:ps_1770_update_order_status_colors(); */[ERROR] 1.7.7.1 PHP - missing file /* PHP:ps_1771_update_customer_note(); */[INTERNAL] /Users/sDib/www/PrestaShop/presta_16124/src/Core/Addon/Module/ModuleManager.php line 280 - Exception: You are not allowed to install modules. #0 /Users/sDib/www/PrestaShop/presta_16124/src/Core/Addon/Theme/ThemeManager.php(345): PrestaShop\PrestaShop\Core\Addon\Module\ModuleManager->install('ps_linklist') #1 /Users/sDib/www/PrestaShop/presta_16124/src/Core/Addon/Theme/ThemeManager.php(226): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeManager->doEnableModules(Array) #2 /Users/sDib/www/PrestaShop/presta_16124/modules/autoupgrade/classes/UpgradeTools/ThemeAdapter.php(92): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeManager->enable('classic') #3 /Users/sDib/www/PrestaShop/presta_16124/modules/autoupgrade/classes/UpgradeTools/ThemeAdapter.php(51): PrestaShop\Module\AutoUpgrade\UpgradeTools\ThemeAdapter->enableTheme17('classic') #4 /Users/sDib/www/PrestaShop/presta_16124/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(681): PrestaShop\Module\AutoUpgrade\UpgradeTools\ThemeAdapter->enableTheme('classic') #5 /Users/sDib/www/PrestaShop/presta_16124/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(118): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->updateTheme() #6 /Users/sDib/www/PrestaShop/presta_16124/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #7 /Users/sDib/www/PrestaShop/presta_16124/admin-dev/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #8 {main}`
> * 1.7.5.2 -> 1.7.7.5
>   `[ERROR] 1.7.6.0 PHP - missing file /* PHP:ps_1760_copy_data_from_currency_to_currency_lang(); */[ERROR] 1.7.6.0 PHP - missing file /* PHP:ps_1760_update_configuration(); */[ERROR] 1.7.6.0 PHP - missing file /* PHP:ps_1760_update_tabs(); */[ERROR] 1.7.6.1 PHP - missing file /* PHP:ps_1761_update_currencies(); */[ERROR] 1.7.6.3 PHP - missing file /* PHP:ps_1763_update_tabs(); */[ERROR] 1.7.7.0 PHP - missing file /* PHP:ps_1770_preset_tab_enabled(); */[ERROR] 1.7.7.0 PHP - missing file /* PHP:ps_1770_update_order_status_colors(); */[ERROR] 1.7.7.1 PHP - missing file /* PHP:ps_1771_update_customer_note(); */`

Thank you for testing, I'll update it :pray:

**Comment by PierreRambaud** [comment]
> @PierreRambaud
> 
> Two upgrades failed with this pr. FO is broken but good news the restoration process is working :p
> 
> * 1.6.1.24 -> 1.7.7.5
>   `[ERROR] 1.7.0.0 PHP - missing file /* PHP:select_current_payment_modules(); */[ERROR] 1.7.0.0 PHP - missing file /* Add Payment Preferences tab. SuperAdmin profile is the only one to access it. */ /* PHP:ps_1700_add_payment_preferences_tab(); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:ps1700_stores(); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:ps_1700_add_locale(); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:add_quick_access_tab(); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(displayProductTab); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(displayProductTabContent); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(displayBeforePayment); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(actionBeforeAuthentication); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(actionOrderDetail); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(actionProductListOverride); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(actionSearch); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(displayCustomerIdentityForm); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(displayHomeTab); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(displayHomeTabContent); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(displayPayment); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:delete_hook(displayProductComparison); */[ERROR] 1.7.0.0 PHP - missing file /* PHP:migrate_tabs_17(); */[ERROR] 1.7.0.0 PHP - missing file /* Properly migrate the rights associated with each tabs */ /* PHP:ps_1700_right_management(); */[ERROR] 1.7.0.5 PHP - missing file /* PHP:ps_update_tabs(); */[ERROR] 1.7.2.0 PHP - missing file /* PHP:drop_column_from_product_lang_if_exists(); */[ERROR] 1.7.2.0 PHP - missing file /* PHP:add_new_status_stock(); */[ERROR] 1.7.3.0 PHP - missing file /* PHP:ps_1730_add_quick_access_evaluation_catalog(); */[ERROR] 1.7.3.0 PHP - missing file /* PHP:ps_1730_move_some_aeuc_configuration_to_core(); */[ERROR] 1.7.3.0 PHP - missing file /* PHP:ps_1730_migrate_data_from_store_to_store_lang_and_clean_store(); */[ERROR] 1.7.4.0 PHP - missing file /* PHP:ps_1740_update_module_tabs(); */[ERROR] 1.7.5.0 PHP - missing file /* PHP:add_supplier_manufacturer_routes(); */[ERROR] 1.7.5.0 PHP - missing file /* PHP:ps_1750_update_module_tabs(); */[ERROR] 1.7.5.1 PHP - missing file /* PHP:ps_1751_update_module_sf_tab(); */[ERROR] 1.7.6.0 PHP - missing file /* PHP:ps_1760_copy_data_from_currency_to_currency_lang(); */[ERROR] 1.7.6.0 PHP - missing file /* PHP:ps_1760_update_configuration(); */[ERROR] 1.7.6.0 PHP - missing file /* PHP:ps_1760_update_tabs(); */[ERROR] 1.7.6.1 PHP - missing file /* PHP:ps_1761_update_currencies(); */SQL 1.7.6.2 1136 in INSERT INTO `ps_product_lang`SELECT`entity`.`id_product`, 1, `entity`.`id_lang`, `entity`.`description`, `entity`.`description_short`, `entity`.`link_rewrite`, `entity`.`meta_description`, `entity`.`meta_keywords`, `entity`.`meta_title`, `entity`.`name`, `entity`.`available_now`, `entity`.`available_later`, `entity`.`delivery_in_stock`, `entity`.`delivery_out_stock`FROM`ps_product_lang`entity LEFT JOIN`ps_product_lang`entity2 ON`entity2`.`id_shop`= 1 AND`entity`.`id_product`=`entity2`.`id_product`WHERE`entity2`.`id_shop` IS NULL: Column count doesn't match value count at row 1[ERROR] 1.7.6.3 PHP - missing file /* PHP:ps_1763_update_tabs(); */[ERROR] 1.7.7.0 PHP - missing file /* PHP:ps_1770_preset_tab_enabled(); */[ERROR] 1.7.7.0 PHP - missing file /* PHP:ps_1770_update_order_status_colors(); */[ERROR] 1.7.7.1 PHP - missing file /* PHP:ps_1771_update_customer_note(); */[INTERNAL] /Users/sDib/www/PrestaShop/presta_16124/src/Core/Addon/Module/ModuleManager.php line 280 - Exception: You are not allowed to install modules. #0 /Users/sDib/www/PrestaShop/presta_16124/src/Core/Addon/Theme/ThemeManager.php(345): PrestaShop\PrestaShop\Core\Addon\Module\ModuleManager->install('ps_linklist') #1 /Users/sDib/www/PrestaShop/presta_16124/src/Core/Addon/Theme/ThemeManager.php(226): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeManager->doEnableModules(Array) #2 /Users/sDib/www/PrestaShop/presta_16124/modules/autoupgrade/classes/UpgradeTools/ThemeAdapter.php(92): PrestaShop\PrestaShop\Core\Addon\Theme\ThemeManager->enable('classic') #3 /Users/sDib/www/PrestaShop/presta_16124/modules/autoupgrade/classes/UpgradeTools/ThemeAdapter.php(51): PrestaShop\Module\AutoUpgrade\UpgradeTools\ThemeAdapter->enableTheme17('classic') #4 /Users/sDib/www/PrestaShop/presta_16124/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(681): PrestaShop\Module\AutoUpgrade\UpgradeTools\ThemeAdapter->enableTheme('classic') #5 /Users/sDib/www/PrestaShop/presta_16124/modules/autoupgrade/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php(118): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->updateTheme() #6 /Users/sDib/www/PrestaShop/presta_16124/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeDb.php(41): PrestaShop\Module\AutoUpgrade\UpgradeTools\CoreUpgrader\CoreUpgrader->doUpgrade() #7 /Users/sDib/www/PrestaShop/presta_16124/admin-dev/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeDb->run() #8 {main}`
> * 1.7.5.2 -> 1.7.7.5
>   `[ERROR] 1.7.6.0 PHP - missing file /* PHP:ps_1760_copy_data_from_currency_to_currency_lang(); */[ERROR] 1.7.6.0 PHP - missing file /* PHP:ps_1760_update_configuration(); */[ERROR] 1.7.6.0 PHP - missing file /* PHP:ps_1760_update_tabs(); */[ERROR] 1.7.6.1 PHP - missing file /* PHP:ps_1761_update_currencies(); */[ERROR] 1.7.6.3 PHP - missing file /* PHP:ps_1763_update_tabs(); */[ERROR] 1.7.7.0 PHP - missing file /* PHP:ps_1770_preset_tab_enabled(); */[ERROR] 1.7.7.0 PHP - missing file /* PHP:ps_1770_update_order_status_colors(); */[ERROR] 1.7.7.1 PHP - missing file /* PHP:ps_1771_update_customer_note(); */`

I update my code, could you tell me if you still reproduce? (because me no :sweat_smile: )

**Review by Progi1984 — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @PierreRambaud & @sarahdib

**Pull request merged**
