### PR TITLE
Rename 8.1.6.sql to 8.1.7.sql

### PR DESCRIPTION
**Pull request by matks**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | See below
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| Sponsor company   | 
| How to test?      | This is a simple file renaming allowing changes scheduled for 8.1.6 release to be done for upgrade from (...) to 8.1.7 instead. You can verify that by performing an upgrade from (example) 8.1.5 to 8.1.7 and verifying one of the SQL scripts written [here](https://github.com/PrestaShop/autoupgrade/blob/dev/upgrade/sql/8.1.6.sql) has been performed, while an upgrade (example) from 8.1.5 to 8.1.6 did not trigger these scripts.

## Description

PrestaShop 8.1.6 was a security release, so we did not bundle all the PRs merged for 8.1.6 in it. Instead, we simply created 8.1.6 by fetching the 8.1.5 tag and then adding the content of the security patch on top of it.

The PRs merged for 8.1.6 on branch 8.1.x have been milestoned 8.1.7 instead and will be delivered with patch release 8.1.7 . Consequently it is necessary to rename file 8.1.6.sql to 8.1.7.sql

### CODE REVIEW

**Review by Quetzacoalt91 — APPROVED** [review]

**Review by M0rgan01 — APPROVED** [review]

**Review by Hlavtox — APPROVED** [review]
@matks Can I merge it or I would get banned?

**Comment by matks** [comment]
> @matks Can I merge it or I would get banned?

CI is red

**Comment by Hlavtox** [comment]
@matks Tru, and we should also ask QA before

**Review by ga-devfront — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
@matks Can you please rebase?

**Comment by matks** [comment]
@Quetzacoalt91 Done ;)

**Review by Quetzacoalt91 — APPROVED** [review]

**Review by AureRita — APPROVED** [review]
Hi @matks 

Thank you for your PR, I tested it and it seems to works as you can see : 

[recording(211).webm](https://github.com/PrestaShop/autoupgrade/assets/100699445/85a44963-6c86-4a15-9cfe-a7a0d8fc1ec2)


Tested from 8.1.5 to 8.1.6 only (because I already check it on other PR) 

Because the PR seems to works as expected, It's QA :heavy_check_mark: 

Thank you

**Review by Hlavtox — CHANGES_REQUESTED** [review]
@AureRita Can you please verify the QA process again?

On your video, you still have 8.1.5 after the upgrade.
Also, you just showed us that your database has changed, but it SHOULD NOT change.

**Comment by AureRita** [comment]
Hi @Hlavtox 

Indeed, the files used was a fake 8.1.6 (?), after used it with a real 8.1.6 that what I have : 

[recording(212).webm](https://github.com/PrestaShop/autoupgrade/assets/100699445/ba8dc032-fd2a-445c-a3cd-3349bc5bf4f1)

TLDS : 

When I use minor release to have the 8.1.6 -> Don't have any changes :heavy_check_mark: 

When I use it with local archive and said it's a 8.1.7 -> Don't have any changes :x:

Currently with the new test, I don't have any modification ... 

FYI to use the same DB I use the rollback to restart on 8.1.5

**Review by AureRita — APPROVED** [review]
Hi @Hlavtox 

Indeed It was a strange version 8.1.6 that I have ( when I load it to a new shop, it write 8.1.5 ... ) 
But, I do the test again and as you can see : 

[recording(213).webm](https://github.com/PrestaShop/autoupgrade/assets/100699445/7cec4ccf-819b-4906-b12d-661227b5c87e)

With a do an upgrade from a minor version to go on 8.1.6, I don't have the changes :heavy_check_mark: 

When I specified that's a 8.1.7, I have the changes :heavy_check_mark: 

So it's QA :heavy_check_mark:

**Review by Hlavtox — APPROVED** [review]

**Pull request merged**
