### PR TITLE
Update 8.1.0.sql, add hook actionProductPriceCalculation

### PR DESCRIPTION
**Pull request by carmas123**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Added new hook to override price calculation
| Type?             | New feature
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | [https://github.com/PrestaShop/PrestaShop/pull/27927
| How to test?      | Added only a new hook
| Possible impacts? | No impact.

### CODE REVIEW

**Review by matthieu-rolland — APPROVED** [review]

**Comment by matthieu-rolland** [comment]
shall we wait for the merge of pr #27927 on develop before merging this one ?

**Comment by carmas123** [comment]
Sorry for my delay but I didn't quite understand what I should do.
Please explain, I'm here

**Review by jolelievre — CHANGES_REQUESTED** [review]
Thanks @carmas123 

sorry, your feature didn't reach the 8.0 scope but it could be integrated into the 8.1.

**Comment by jolelievre** [comment]
Closed in favor of https://github.com/PrestaShop/autoupgrade/pull/525
Sorry @carmas123 I tried to update your branch to update this PR but I failed, I was able to rebase your dev branch (which is now in sync with the repo 😅) but I couldn't push the modification

For your future PRs (including for the core) please don't use the same names as the protected branches, prefer a naming related to your PR content, this way you can have multiple branches for multiple PRs and it's easier to modify them for maintainers (dev branches are often protected)

**Pull request closed without merging**
