### PR TITLE
Merge changes from `6.x` branch to `dev`

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Cherry pick of https://github.com/PrestaShop/autoupgrade/pull/1009 and https://github.com/PrestaShop/autoupgrade/pull/1035
| Type?             | improvement
| BC breaks?        | Nope
| Deprecations?     | Nope
| Fixed ticket?     | /
| Sponsor company   | /
| How to test?      | See related line in PRs

### CODE REVIEW

**Comment by Hlavtox** [comment]
@Quetzacoalt91 Thomas, could you also check vice versa? Do we have any changes that need backport dev > 6?

**Comment by Quetzacoalt91** [comment]
We deal mostly with improvements and the Update Assistant v7 will be released before PrestaShop v9, so at the moment I don't see any PR in particular to send on the branch `6.x`.

**Comment by Hlavtox** [comment]
@Quetzacoalt91 In that case, no need, if v7 will be ready. :-)

**Review by ga-devfront — APPROVED** [review]

**Review by AureRita — APPROVED** [review]
Hi @Quetzacoalt91 

Thank you for your PR, I tested it and it seems to works as you can see : 

image

image


Because the PR seems to works as expected, It's QA :heavy_check_mark: 

Thank you

**Comment by ps-jarvis** [comment]
PR merged, well done!

Message to @PrestaShop/committers: do not forget to milestone it before the merge.

**Pull request merged**
