### PR TITLE
Normalize NULL data in database

### PR DESCRIPTION
**Pull request by M0rgan01**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | This PR repeats the work of the PR https://github.com/PrestaShop/autoupgrade/pull/605, adding a php function call
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #https://github.com/PrestaShop/PrestaShop/issues/33371, Fixes #https://github.com/PrestaShop/PrestaShop/issues/25996, Fixes #https://github.com/PrestaShop/PrestaShop/issues/22862, Fixes #https://github.com/PrestaShop/PrestaShop/issues/22386, Fixes #https://github.com/PrestaShop/PrestaShop/issues/22215
| Sponsor company   | -
| How to test?      | see below

To verify that the script has been executed, there are several solutions:

- if 8.1.3 is already released, perform an upgrade process from 8.0 to 8.1.3.
- if 8.1.3 is not released, copy the content of the changes from the 8.1.3 script to the 8.1.2 script and upgrade from 8.0.x to 8.1.2

There will be almost no change on a fresh install,

### CODE REVIEW

**Comment by Hlavtox** [comment]
We should also set the default values, or it can get broken again. 👍

**Comment by M0rgan01** [comment]
@Hlavtox thank you, I modified accordingly

**Review by tleon — DISMISSED** [review]

**Comment by M0rgan01** [comment]
I'm passing the subject to draft, I have to review elements on default values

**Comment by Hlavtox** [comment]
One more question - do we keep the columns NULLABLE or not? 👍

@jolelievre

**Comment by M0rgan01** [comment]
@Hlavtox after reflection, we cannot modify all of the columns concerned on a core patch, it would have to be done on a major version. This would result in breaking changes.

Executing these requests does not solve the problem in any way, it is simply a mitigation of the problem while waiting for v9 and a potential (real) fix.

**Comment by Hlavtox** [comment]
@M0rgan01 I tested the script and it works properly.

In order not to run the whole upgrade, I copied the method into IndexController and called it with $this->update_null_values();, all queries went OK.

However, I have one improvement I think we can do. Do you think you could add this before running the query? Maybe we will re-run it for v9 and I want to avoid some missing columns that we decide to remove in the meantime.

```php
            // Check if the table exists
            if (empty($db->executeS('SHOW TABLES LIKE "' . _DB_PREFIX_ . $tabName . '"'))) {
                continue;
            }

            // Check if the column exists
            if (empty($db->executeS('SHOW COLUMNS FROM `' . _DB_PREFIX_ . $tabName . "` WHERE Field = '" . $columnName . "'"))) {
                continue;
            }
```

**Comment by M0rgan01** [comment]
@Hlavtox good idea, I added it, thanks

**Review by Hlavtox — APPROVED** [review]

**Comment by Hlavtox** [comment]
Works perfectly.

Tried adding
```php
['webservice_account', 'dasdsadas', ''],
['dasdasd', 'dasdsadas', ''],
```
and they are skipped with no error. 👍

**Pull request merged**
