### PR TITLE
Remove product page v2 feature flag

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Remove product page v2 feature flag since it is removed by this PR https://github.com/PrestaShop/PrestaShop/pull/33587
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | ~
| Sponsor company   | ~
| How to test?      | ~

### CODE REVIEW

**Review by mflasquin — DISMISSED** [review]

**Comment by Progi1984** [comment]
Don't forget UI tests @boubkerbribri

**Review by boherm — DISMISSED** [review]

**Review by matthieu-rolland — DISMISSED** [review]

**Comment by matks** [comment]
@jolelievre why did you remove the "waiting for QA" label?

**Review by matks — APPROVED** [review]

**Review by M0rgan01 — APPROVED** [review]

**Comment by boubkerbribri** [comment]
> > @jolelievre why did you remove the "waiting for QA" label?
> 
> I think this is because a discussion is happening with QA automation team. When the feature flag is forced to ON, this disables forever product page v1 which is used by automated tests.

Not automation but maybe functional team

**Review by tleon — DISMISSED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @jolelievre ,

The branch has conflicts, could you check please ?
Screenshot 2024-02-14 at 16 51 03

Thanks :D

**Review by M0rgan01 — APPROVED** [review]

**Comment by jolelievre** [comment]
Thanks @florine2623 it's ok now!

**Review by tleon — APPROVED** [review]

**Review by florine2623 — COMMENTED** [review]
Hello @jolelievre ,

Tested the module with these upgrades :
- 8.0.5 > 9.0.0
- 8.1.4 > 9.0.0
- 8.0.5 > 8.1.3 > 9.0.0

All upgrades were not successful. The issue doesn't come from the PR. My server must have a problem...

@PrestaShop/qa-functional could you check please ?

**Comment by jolelievre** [comment]
I don't know if it's related but I've seen an issue about the upgrade being impossible towards develop branch recently https://github.com/PrestaShop/PrestaShop/issues/35029

Maybe it's related? If so it seems we can validate no PRs regarding the v9 upgrade until this is fixed

**Comment by AureRita** [comment]
Hi, 

Because of your verdict @jolelievre I think I can put this PR into blocked until we can upgrade to 9.0.0

Waiting for feedback

**Review by boherm — APPROVED** [review]

**Comment by ga-devfront** [comment]
@jolelievre I think you have to rebase from dev

**Comment by jolelievre** [comment]
@AureRita perfect then, I close this one

**Pull request closed without merging**
