### PR TITLE
Release 5.0.0

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Release 5.0.0
| Type?             |
| BC breaks?        | 
| Deprecations?     | 
| Fixed ticket?     | 
| Sponsor company   | 
| How to test?      |

### CODE REVIEW

**Comment by Hlavtox** [comment]
Ping @PrestaShop/committers, we can merge it, contains only 1 PR tested by @aniszr

**Review by matthieu-rolland — DISMISSED** [review]

**Review by boherm — APPROVED** [review]

**Review by jolelievre — CHANGES_REQUESTED** [review]
We won't release the version right now, we are currently working on an improvement to remove Doctrine command from the upgrade process It will also include the recent changes on the DB structure but before we release it we want to test this thoroughly with automated tests that are also under development

**Comment by Hlavtox** [comment]
❗ Dont release this now, 8.1.2 scripts need to be moved to 8.1.3.

**Comment by Hlavtox** [comment]
@jolelievre Removing the block, it has been two months and the feature is not yet developed. There are more important fixes to be delivered. 👍

**Review by ShaiMagal — APPROVED** [review]
Ready

**Review by jolelievre — DISMISSED** [review]
Just blocking this as the version number should be 5.0.0

**Comment by matks** [comment]
See https://github.com/PrestaShop/autoupgrade/pull/658

**Review by kpodemski — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by paulnoelcholot** [comment]
Hello @Hlavtox,

@AureRita and I tested your PR and it's GOOD for us! :tada: 

Thanks!

We only encountered this bug, but it is not related to the release, but related to MBO
image

**Pull request merged**
