### PR TITLE
Release 4.14.1

### PR DESCRIPTION
**Pull request by matks**
**Warning**: this PR targets `master` branch, and not `dev` branch. This is a hotfix, so it branched out to `master` branch and will need to be backported to `dev` branch after the merge.

| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Release 4.14.1. This release only contains the 2 commits needed for 1.7.x -> 1.7.8.6 upgrades, nothing more.
| Type?             | improvement

## Context

When the time to do a new release for upgrade module came, we found possible issues (see https://github.com/PrestaShop/autoupgrade/pull/481). In order not to delay anymore the release of PrestaShop 1.7.8.6 I submit this hotfix PR for `master` branch that contains only the needed items for 1.7.x -> 1.7.8.6 . The goal is to un-block the 1.7.8.6 release.

## How to test

I provided below a list of the changes between 4.14.1 and 4.14.0

https://github.com/PrestaShop/autoupgrade/pull/455
https://github.com/PrestaShop/autoupgrade/pull/474

### CODE REVIEW

**Review by atomiix — APPROVED** [review]

**Comment by hibatallahAouadni** [comment]
Hello @matks 

Thanks for the release!

Tested by @marwachelly & @khouloudbelguith 

Autoupgrade 1.7.6.7 to 1.7.7.8 Mysql 5.7+php 7.1 => (Check BO & FO ) => OK
Rollback 1.7.7.8 to 1.7.6.7 => (Check BO & FO ) => OK
Autoupgrade 1.7.7.8 to 1.7.8.5 mysql 8.0 + php 7.2 => (Check BO & FO ) => OK
Rollback 1.7.8.5 to 1.7.7.8 => (Check BO & FO ) => OK
we detected an error when upgrading from 1.7.7.8 (php7.2) to PS1.7.8.6 (release from the branch 1.7.8.x)
Fresh install of Ps 1.7.7.8 and installed with arabe language

image

---
Tested by me

### 1.6.1.24 -> 1.7.8.5 
The upgrade is success :heavy_check_mark: 
image

But I encountred some issues on FO:
- **1st issue:** modal bad displayed for the new products (not pre-install added) and the product image are bad displayd

https://user-images.githubusercontent.com/23308427/165981280-4e6522d8-0388-493b-8a86-b25ba5040c97.mp4

- **2nd issue:** in my account, the blockwishlist and My alerts are bad displayed
image

- **3rd issue**: when you try to click on My alerts or Favorites( block wish list) => **error 500**

https://user-images.githubusercontent.com/23308427/165981525-d0afc534-d6be-4209-9d82-1c0711b96c37.mp4

### 1.7.7.8 -> 1.7.8.6
The upgrade is success :heavy_check_mark: 
image

But, I encounter some issue on FO:
- **1st issue:** searchbar is bad displayed (known issue) :wink: 
image

- **2nd issue:** modal bad displayed
image

### 1.7.7.8 (Arabic install) -> 1.7.8.6
Upgrade Succes :heavy_check_mark: 
image

I encountred some issues:
- **1st issue:** bad display of module
image
image

- **2nd issue:** the logo in Delivery Slip and Invoice run away :grin: I encounter this issue only with this shop installed in Arabic
image

BTW, I didn't encounter the issue of searchbar with this version :sweat_smile: 
image

image

---
@Robin-Fischer-PS it's your call if we need to investigate more the issues that we encountred or not?

Thanks!

**Comment by matks** [comment]
@hibatallahAouadni When you say "known issues", do you mean there is already a bug report?

**Comment by hibatallahAouadni** [comment]
@matks Yesss!

**Comment by matks** [comment]
@hibatallahAouadni If I read through your report, I focus on X -> 1.7.8.6 upgrades and I ignore the known issues it looks like only blocking issue is an error when upgrading from 1.7.7.8 (php7.2) to PS1.7.8.6 ; using fresh install of Ps 1.7.7.8 and installed with arabe language.

Is that correct?

(I created a bug report for this https://github.com/PrestaShop/PrestaShop/issues/28394)

**Comment by kpodemski** [comment]
This problem with the logo is related to tcpdf issues, I remember it was this or deleting images from the server 😕 (two bugs from tcpdf on a different versions)

**Comment by hibatallahAouadni** [comment]
Hello @matks 

> only blocking issue is an error when upgrading from 1.7.7.8 (php7.2) to PS1.7.8.6 ; using fresh install of Ps 1.7.7.8 and installed with arabe language.

This issue is reproduced by @marwachelly, I tried to reproduce it but I didn't encountred :disappointed: 
The only issue that I encountered and it's kind of a regression is when I upgraded from 1.6.1.24 to 1.7.8.5:
- **2nd issue:** in my account, the blockwishlist and My alerts are bad displayed
image

- **3rd issue**: when you try to click on My alerts or Favorites( block wish list) => **error 500**

https://user-images.githubusercontent.com/23308427/165981525-d0afc534-d6be-4209-9d82-1c0711b96c37.mp4

Thanks!

**Review by marwachelly — APPROVED** [review]
Hello, 

Please find bellow the list of version tested by @PrestaShop/qa-functional. No regression related to the release is detected:
 
- autoupgrade and rollback 1.7.6.7 to 1.7.7.8 (Full test)
- autoupgrade and rollback 1.7.7.8 to 1.7.8.5 (Full test)
- autoupgrade and rollback 1.7.7.8 to 1.7.8.6 (Full test)
- autoupgrade and rollback 1.7.8.0 to 1.7.8.5 (simple upgrade)
- autoupgrade and rollback 1.6.1.24 to 1.7.8.5 (Full test)
- autoupgrade and rollback 1.7.6.9 to 1.7.8.5 (Simple upgrade)
- autoupgrade and rollback 1.7.6.9 to 1.7.8.6 (Functional test after upgrade)
- autoupgrade and rollback 1.7.6.5 to 1.7.8.6 (Full test)
- autoupgrade and rollback 1.7.8.3 to 1.7.8.6 (Full test)
- autoupgrade and rollback 1.7.7.8 to 1.7.8.6 (Full test)
- autoupgrade and rollback 1.7.4.2 to 1.7.8.6 (Full test)
- autoupgrade and rollback 1.6.1.24 to 1.7.8.6 (Full test)

So Release is QA :heavy_check_mark:

Thank you,

**Pull request merged**
