### PR TITLE
feat: storybook repository dispatch draft

### PR DESCRIPTION
**Pull request by JMorinPS**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | CICD implementation to bring online Autoupgrade storybook
| Type?             | new feature
| BC breaks?        | yes (Dockerfile, Docker Compose=
| Deprecations?     | no
| Fixed ticket?     | NA
| Sponsor company   | PrestaShop
| How to test?      | Navigate to public URL to see changes

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hello @JMorinPS!

This is your first pull request on [autoupgrade](https://github.com/PrestaShop/autoupgrade/) repository of the PrestaShop project.

Thank you, and welcome to this Open Source community!

**Review by Quetzacoalt91 — DISMISSED** [review]

**Review by ga-devfront — DISMISSED** [review]

**Comment by ga-devfront** [comment]
@JMorinPS We got a problem with conflict files.

**Comment by Quetzacoalt91** [comment]
@ga-devfront I rebased and dropped the commit responsible of the conflict

**Review by djodjo3 — APPROVED** [review]

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by ps-jarvis** [comment]
PR merged, well done!

Message to @PrestaShop/committers: do not forget to milestone it before the merge.

**Pull request merged**
