### PR TITLE
Adapt upgraded installs to recent changes

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Implements required database changes for recent 9.0.0 PRs.
| Type?             | refactor
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| Sponsor company   | 
| How to test?      | Run upgrade from 8.1.x to develop and check if it ran correctly. I ran everything in database admin and works correctly.

### List of PRs
- https://github.com/PrestaShop/PrestaShop/pull/33363
- https://github.com/PrestaShop/PrestaShop/pull/33232
- https://github.com/PrestaShop/PrestaShop/pull/31151
- https://github.com/PrestaShop/PrestaShop/pull/33158

### CODE REVIEW

**Review by ShaiMagal — APPROVED** [review]
LGTM

**Review by matthieu-rolland — APPROVED** [review]

**Comment by AureRita** [comment]
Hi @Hlavtox 

Thank you for this PR, I tested it and I see something : 

[recording(49).webm](https://github.com/PrestaShop/autoupgrade/assets/100699445/1caca385-381c-45db-9d47-6075253e6f17)

It seems to not load the change that you give with the first three PR 

About the last one, all seems to works except that you can search warehouse : 
image

And your stock isn't calculated with Product return as you can see : 

[recording(50).webm](https://github.com/PrestaShop/autoupgrade/assets/100699445/46c40b6f-c163-4fa9-9365-516df07f794d)

Thank you

**Comment by Hlavtox** [comment]
I see what you mean, but yeah, typing nonsense into the URL bar will get you this message. On all prestashop versions. I don't know what it has to do with my PR.

Snímek obrazovky 2024-01-10 174411

**Review by florine2623 — APPROVED** [review]
Seen with @Hlavtox ,

At the moment the module can't be tested with an upgrade to 9.0.0, because of this error https://github.com/PrestaShop/PrestaShop/issues/35029

Although, the queries that are added to the module have been tested manually on phpmyadmin. And it is OK. All the queries are well executed.

Screenshot 2024-01-11 at 15 39 39

It is OK on QA side ✅

**Comment by Hlavtox** [comment]
Thank you @florine2623! :-)

**Pull request merged**
