### PR TITLE
Ordered imports

### PR DESCRIPTION
**Pull request by MathiasReker**

### CODE REVIEW

**Comment by PierreRambaud** [comment]
Waiting for feedback to check if this one is really useful, (I'm the only one who check orders :roll_eyes: )

**Comment by matks** [comment]
I find it useful but it will create git conflicts. Is it worth it, considering that we look very few at imported classes ?

**Comment by matks** [comment]
I would be more in favor of a "scout" approach: everytime you work on a class, first you apply refactoring / lint steps such as this one, then you work on it.

**Comment by MathiasReker** [comment]
I commented out this part from my script for now :)

**Comment by MathiasReker** [comment]
Thank you :)

**Pull request closed without merging**
