### PR TITLE
Fix line not compatible with PHP < 7

### PR DESCRIPTION
**Pull request by Prestaworks**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Fix for issue 27087
| Type?             | bug fix
| BC breaks?        |  no
| Deprecations?     |  no
| Fixed ticket?     | Related to PrestaShop/PrestaShop#27087.
| How to test?      | See Issue for details.
| Possible impacts? |

### CODE REVIEW

**Review by atomiix — DISMISSED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by eternoendless** [comment]
Note: this PR is valid and will fix the bug as reported in the issue, but won't fully resolve the underlying issue itself (refer to the "steps to fix" part described in the issue).

**Review by florine2623 — CHANGES_REQUESTED** [review]
Hello @Prestaworks ,

Thanks for the PR !

Here's what has been tested :

- upgrade from 1.6.1.19 to 1.6.1.24 (_PHP 5.6_) ⛔ 
I encountered this error, I can't complete the upgrade: 
Screenshot 2022-02-23 at 17 13 40

- upgrade from 1.6.1.24 to 1.7.4.0 (_PHP 5.6_) ⛔ 
Upgrade went well, but there are some issues regarding the display of the shop.
Then, I wanted to upgrade to 1.7.8.3 (PHP 7.1) ⛔ 
The autupgrade module doesn't work, no more updates can be done. In the expert mode options, everything is displayed :
Screenshot 2022-02-23 at 17 40 49

- upgrade from 1.7.8.x to develop (PHP 7.3) ⛔ 
Thanks @marwachelly for testing this one
The upgrade cannot be completed : https://watch.screencastify.com/v/KpAbLxMizrGB21DcRUWW
Without PR, the upgrade works well ✅ 

All tests were done with autoupgrade v1.14.0.

Could you take a look please ?
Thanks!

**Comment by Prestaworks** [comment]
Hi @florine2623 
This PR is not included in the v1.14.0

**Review by florine2623 — COMMENTED** [review]
Hello @Prestaworks ,

Sorry I wasn't clear ! I, of course, used v1.14.0 + installed the PR, then did the upgrade ^^
Could you send me a screen record of the result of your PR ?
Of the exact steps that you used so I can reproduce it on my end ?

Thanks!

**Comment by Prestaworks** [comment]
> Hello @Prestaworks ,
> 
> Sorry I wasn't clear ! I, of course, used v1.14.0 + installed the PR, then did the upgrade ^^ Could you send me a screen record of the result of your PR ? Of the exact steps that you used so I can reproduce it on my end ?
> 
> Thanks!

Are you sure? 
If I look at the error in the image you added
"CoreUpgrader line 195 - dirname() expects exactly 1 parameter, 2 given"
and then the error that it can't include a file from /upgrade/ folder

now this is the error the PR should fix and if the PR had been included and there where some kind of error trying to find the file
the path should have started with /autoupgrade/upgrade/

so based on the error in the first image, I would guess that the PR was not applied.

**Comment by Prestaworks** [comment]
@florine2623 did you have time to check this?

**Review by florine2623 — CHANGES_REQUESTED** [review]
Hello @Prestaworks ,

Sorry for the long answer.

For these tests, I did upgrades 
- with and without PR
- to Stable versions and develop versions
- using PHP 5.6 and 7.2

Here's a recap of all the tests I've done. I'm using PHP 5.6 in all the following cases :
| Upgrade | Without PR | With PR | 
| ------------- | ------------- | ------------- |
| 1.6.1.24 ➡️  1.7.4.4  | Screenshot 2022-03-22 at 15 49 51 ⛔  | Screenshot 2022-03-22 at 15 39 56 autoupgrade module is NOK after installing PR ⛔  | 
| 1.6.1.24 ➡️  1.7.6.5  | Screenshot 2022-03-22 at 15 52 10 ⛔  | Screenshot 2022-03-22 at 15 47 24 NOK with PR, can't access the module autoupgrade in BO ⛔  | 
| 1.7.3.4 ➡️  1.7.5.2  | Screenshot 2022-03-22 at 16 03 46 ⛔  | Screenshot 2022-03-22 at 15 57 04 NOK with PR ⛔   |


Here I am using PHP 7.2 :
| Upgrade | Without PR | With PR |
| ------------- | ------------- | ------------- |
| 1.7.7.8 ➡️  develop  | Screenshot 2022-03-22 at 15 12 20 ⛔  | Screenshot 2022-03-22 at 15 13 24 error when trying to go to FO ⛔ |
| 1.7.8.5 ➡️  develop  |Screenshot 2022-03-22 at 15 14 38 ⛔  |Screenshot 2022-03-22 at 15 15 09 error with ps_facebook, but when deleted OK ✅ Screenshot 2022-03-22 at 15 29 37  |



This is not approved by QA.

**Comment by Prestaworks** [comment]
> 

Hi Florine,

do you have access to your error logs to see why you get a 500 error?

**Comment by Prestaworks** [comment]
Another Question for you @florine2623 the error you get in 1.6.1.24
bild

is that when you click on "configure" for the module?

**Comment by Prestaworks** [comment]
I made another file php 5.6 compliant.
running a upgrade by
1. install fresh 1.6.1.24
2. Install autoupgrade
3. apply both file changes from PR
4. run install process
Screenshot 2022-03-31 at 13-16-57 1-Click Upgrade 1-Click Upgrade • testupgrade

**Review by jolelievre — APPROVED** [review]
Thanks @okom3pom

**Comment by okom3pom** [comment]
@jolelievre  I think you want say : thank @Prestaworks 

:dancers:

**Comment by jf-viguier** [comment]
@florine2623 can you check ? @Prestaworks fixed the issue on 31 march ?

**Comment by jolelievre** [comment]
@okom3pom ah yes my bad Thanks (and sorry) @Prestaworks 
I reviewed a bunch of PR on autoupgrade and I messed with the authors, my bad 😅

**Review by florine2623 — COMMENTED** [review]
Hello @Prestaworks ,

As tested by me and @sLorenzini , we can't finish an upgrade properly without bug.
Here's the report :

**PHP 5.6**

- PS 1.7.2.5 => PS 1.7.8.6 NOK ❌ 
  
Screenshot 2022-07-04 at 11 45 39

- PS 1.7.4.3 => PS 1.7.8.6 NOK ❌ 

Screenshot 2022-07-04 at 11 40 46

- PS 1.6.1.22 => PS 1.7.8.0
    * with PR => NOK ❌ 
Screenshot 2022-07-04 at 17 21 58
    * without PR => NOK, BO not accessible ❌  
    
https://user-images.githubusercontent.com/16019289/177560729-d7945793-3322-44f7-bee9-4e797dc9aa5b.mp4

- PS 1.7.5.0 => PS 1.7.8.6
    * Same error as PS 1.7.4.3 => PS 1.7.8.6
    * Without PR => NOK, table `ps_currency_lang` is missing, has to be added manually to make it work

**PHP 7.1**

- `PS 1.7.7.7 => 8.0.0` & `PS 1.7.8.0 => 8.0.0` ❌ error composer
Screenshot 2022-07-04 at 17 22 29


Capture d’écran 2022-07-05 à 16 59 22

Thanks ^^

PS : @PrestaShop/qa-team if someone could check this PR that would be great !

**Comment by okom3pom** [comment]
Hello @florine2623 

You have to check only 1.6.1.x to 1.7.5x or 1.7.6.x with php 5.6 

I think the how to test need top be updated 

https://devdocs.prestashop.com/1.7/basics/installation/system-requirements/

**Review by khouloudbelguith — COMMENTED** [review]
Hi @Prestaworks,

I tried an upgrade from PS1.6.1.20 => PS1.6.1.24 + php5.6 : OK

https://user-images.githubusercontent.com/16067358/189386252-837ae767-82cb-4e60-ad3b-b3f966317493.mp4


I tried an upgrade from PS1.6.1.24 => PS1.7.6.9 + php5.6: NOK
I attached a screen record

https://user-images.githubusercontent.com/16067358/189386402-1be85a0c-da90-4522-8fb6-c6a7d2b5eebe.mp4

Thanks to check and feedback

**Comment by Prestaworks** [comment]
> 

To be frank, it looks like files and DB are all OK but it fails on faceted search module. That is not related to this PR. Maybe you can try an upgrade and set the setting to NO for upgrading all modules? if not, the ps_facetedsearchmodule would have to be fixed first, for you to approve a fix for the core upgrade.

**Comment by Prestaworks** [comment]
@khouloudbelguith do you have time to check this?

**Review by florine2623 — COMMENTED** [review]
Hello @Prestaworks ,

Sorry for the long answer.

I am using PHP 5.6. I followed your steps:
- Fresh install of 1.6.1.24
- Install autoupgrade v1.14.2 
- Install PR autoupgrade
- Upgrade to 1.7.4.4 successful 

Screenshot 2023-01-27 at 10 47 08

BO is OK
Screenshot 2023-01-27 at 11 01 48

But FO is broken, cache is cleared :
Screenshot 2023-01-27 at 11 02 26

For me it is QA :x: 😞

**Comment by Prestaworks** [comment]
@florine2623 the upgrade went well, turning of development mode should probobly fix the frontend also.
Maybe this is a bit to technical? and we need a developer to review it instead of QA?

**Comment by florine2623** [comment]
@Prestaworks , with debug mode disabled, I just have this : 
Screenshot 2023-01-27 at 11 11 04

It is not that technical, any QA member can test it ^^
It's just that the expected result is not correct 😞

**Comment by Prestaworks** [comment]
> @Prestaworks , with debug mode disabled, I just have this : Screenshot 2023-01-27 at 11 11 04
> 
> It is not that technical, any QA member can test it ^^ It's just that the expected result is not correct 😞

Problem is that QA has tested this for one year now, and you keep hitting issues that is not related to the upgrade module.
The front end is not working due to a missing variable in a module tpl file has nothing to do with the upgrade process, and the upgrade was successfull. So I still think this needs a dev to take a look at instead.

**Comment by SharakPL** [comment]
FO should be broken when it still uses 1.6's default-bootstrap theme on 1.7. Right?

**Comment by florine2623** [comment]
ping @PrestaShop/product-team ,
autoupgrade v4.15.0 is out and available from PS 1.7.0.0 https://github.com/PrestaShop/autoupgrade/blob/v4.15.0/autoupgrade.php#L58

If this PR works and is merged, is there going to be another v4.14.x release just for this PR ?

**Comment by florine2623** [comment]
@PrestaShop/prestashop-core-developers ,

Could you check this PR ? It is not validated by QA.

**Review by nicosomb — COMMENTED** [review]
Hello @Prestaworks. Thank you for this PR. 

I wanted to "request changes" and block this PR. I won't be so radical, I will only give my opinion. 

When you opened it, PHP 5.x was still dead.
Since december 2021, PHP 7.x is dead too. 
I know that PrestaShop 1.7.8.x supports PHP 5.6 and the bug is there, in fact. PrestaShop should require PHP >= 8.0, at least PHP 7.4. 

I understand that this PR is important for you, but for me, we should close it and should work to drop PHP 7x support.

**Comment by Prestaworks** [comment]
> Hello @Prestaworks. Thank you for this PR.
> 
> I wanted to "request changes" and block this PR. I won't be so radical, I will only give my opinion.
> 
> When you opened it, PHP 5.x was still dead. Since december 2021, PHP 7.x is dead too. I know that PrestaShop 1.7.8.x supports PHP 5.6 and the bug is there, in fact. PrestaShop should require PHP >= 8.0, at least PHP 7.4.
> 
> I understand that this PR is important for you, but for me, we should close it and should work to drop PHP 7x support.

Yes, but consider that this is for the autoupgrade module, it is expected to be able to upgrade a Prestashop 1.6 or even an 1.5 or older to Presatshop 8. How do you suggest doing that if the autoupgrade module requires php 7+ when Presastahop 1.6 requires 5.6?

**Comment by nicosomb** [comment]
> How do you suggest doing that if the autoupgrade module requires php 7+ when Presastahop 1.6 requires 5.6?

Upgrade between major versions is not mandatory for me. 
In major versions, you can break everything. I understand it could be a pain for users, and it's only my opinion, not the PrestaShop team's one.

**Comment by matks** [comment]
> How do you suggest doing that if the autoupgrade module requires php 7+ when Presastahop 1.6 requires 5.6?

Well you can use older autoupgrade module versions 🤔 

For example
- Use module version 3 to upgrade from PS 1.5 to PS 1.6
- Use module version 4 to upgrade from PS 1.6 to PS 1.7
- Use module version 5 (new version?) to upgrade from PS 1.7 to PS 8

**Comment by Prestaworks** [comment]
> 

sure, but that would have to be well documentet and addons set up so that the shop owners on older version like 1.6.1.5 do not get the the wrong version of the autoupgrade module like they do now. 
Downloading the latest version from addons fails the upgrade if you use php5.6 and if you use 7+ the shop do not work. 
If you think these two lines cause issues for php8 users just block the merge and I close the PR, I'm kind of tired anyway of spending time on this when I can just fork it for myself instead :)

**Comment by jf-viguier** [comment]
@Prestaworks You've my support, I understand you're tired of answering for 2 lines of php.

**Comment by okom3pom** [comment]
For me no need discussion .... 

Screenshot


Screenshot


Or we have to change the doc or make a major version this PR come from 2021

**Comment by okom3pom** [comment]
Please consider that 1.6 versions are PHP 7 compatible and that 1.7.X versions are PHP 5.6 compatible
We must respect the code and the doc even if it may seem strange

**Comment by FabienPapet** [comment]
There is too much time lost on this PR for testing for such a small feature. I'd go to merge it as it is if everyone agrees.

**Review by FabienPapet — APPROVED** [review]

**Comment by Robin-Fischer-PS** [comment]
Hi there,

On QA side, since we have some issues that @Prestaworks cannot reproduce (and I'm also not sure it's related, given the two lines modified in this PR), it can be validated by a dev without any more QA.

**Comment by matks** [comment]
> There is too much time lost on this PR for testing for such a small feature. I'd go to merge it as it is if everyone agrees.

PHP5 is dead but I agree with @FabienPapet too much time lost. Let's move forward.

**Review by matks — APPROVED** [review]

**Review by MatShir — CHANGES_REQUESTED** [review]
Can a @PrestaShop/prestashop-core-developers confirm this statement ?
I thought we couldn't merge this PR in dev since the version 4.15 is only compatible for 1.7 to 8. We might need to release a patch for 4.14 which is compatible from 1.6 to 1.7.

A doc is in progress on the subject with @kpodemski, even without the version split, upgrading from 1.6 is a long journey!

**Comment by MatShir** [comment]
@PrestaShop/prestashop-core-developers don't hesitate to dismiss my request if it is not relevant here, I might get confused

**Review by nicosomb — APPROVED** [review]

**Comment by nicosomb** [comment]
@MatShir I opened a new PR for v.4.14.x https://github.com/PrestaShop/autoupgrade/pull/585

**Review by MatShir — APPROVED** [review]

**Comment by hibatallahAouadni** [comment]
Hello everyone,

As @Robin-Fischer-PS mentioned above this PR could be tested by Dev:
> Hi there,
>
> On QA side, since we have some issues that @Prestaworks cannot reproduce (and I'm also not sure it's related, given the two lines modified in this PR), it can be validated by a dev without any more QA.

Thanks!

**Comment by mflasquin** [comment]
It's not possible to update PS 1.7.6.x to 8 with PHP 5.6. Because you will have errors on composer dependencies that require php >= 7.2 :

image


image

**Comment by matks** [comment]
> It's not possible to update PS 1.7.6.x to 8 with PHP 5.6.

It's true, but the goal of this PR is to fix the usecase where someone, for example, upgrades from PS 1.7.5 to 1.7.6 using php5.6 . Both versions 1.7.5 and 1.7.6 support php5.6 .

If I read first post https://github.com/PrestaShop/PrestaShop/issues/27087 this is the reasoning: the `4.14.x` of module upgrade says “I allow people to upgrade from 1.6 up to 1.7".

It means
- an upgrade from 1.6.1.18 to 1.6.1.24 using php5.6 should be possible
- an upgrade from 1.6.1.22 to 1.7.3 using php5.6 should be possible
- an upgrade from 1.7.3 to 1.7.6 using php5.6 should be possible
- an upgrade from 1.7.5 to 1.7.8 using php7.0 should be possible (because 1.7.8 requires php higher than 5.6)

However an upgrade from 1.7.6.x to 8.x cannot happen with php5.6

In order for users of the upgrade module to benefit from the value of this PR, I changed the target from `dev` to `4.14.x` branch. This will allow this PR to be merged inside `4.14.x` branch which aims to provide upgrades from 1.6 up to 1.7 . Branch `dev` does not support 1.6 upgrades so this PR would not be very useful.

**Review by matks — APPROVED** [review]
I have checked the code
- with php5.6.37 and I confirm the warning is thrown
- with php7.1.22 and I confirm the warning is not thrown

So it's valid for me 👍

**Comment by MatShir** [comment]
Friendly reminder @matks ;)

**Comment by matks** [comment]
Aaaah

I remember why this PR was not merged @MatShir 

The upgrade module has a feature where it checks whether there is a more recent version of itself and if it does, it tells the user "please use the latest version, you are using an outdated version"

So if we merge this PR in branch `4.14.x` and then we release a version `4.14.2` it's going to be useless.

Because if someone installs the module 4.14.2 on a shop, the module will detect there is a  4.1§.2 version and says to user "please don't use me! use the latest 4.16.2 version instead!"

This is because we never had 2 branches for the upgrade module. We always had only one branch, the latest.

So the branch `4.14.x` will not be useful unless we also introduce a PR in `4.14.x` that modifies/removes this check.

I merge this PR because it is valid but I'm afraid if we don't do the above it will be useless.

**Comment by matks** [comment]
Thank you @Prestaworks 😉

**Comment by matks** [comment]
Gonna try a 4.14.3 release with this fix https://github.com/PrestaShop/autoupgrade/pull/626

**Pull request merged**
