### PR TITLE
Create hacktoberfest2021

### PR DESCRIPTION
**Pull request by luckysharma05**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Please be specific when describing the PR. Every detail helps: What are you changing? Why?
| Type?             | bug fix / improvement / new feature / refacto / critical
| BC breaks?        | yes / no
| Deprecations?     | yes / no
| Fixed ticket?     | Fixes {paste the issue here}.
| How to test?      | Please indicate how to best verify that this PR is correct.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

### CODE REVIEW

**Comment by matks** [comment]
Please do not open spam pull requests, you are hampering the work happening on this open source project.

**Comment by luckysharma05** [comment]
This is what happening everywhere, I am doing a survey on this, that's why
I did a spam pull request just to see that you really open it or just merge
it blindly.
Thank you for your response

**Comment by matks** [comment]
> This is what happening everywhere

Sad :(

> to see that you really open it or just merge it blindly

If someone merge PRs blindly, I suppose it's not a serious open source project.

**Comment by luckysharma05** [comment]
Yes, its quite a bad thing for the open source contribution, which we have
to remove inorder to make open source a good opportunity to showcase your
skills

**Comment by luckysharma05** [comment]
Hey bro why you marked my pull request as spam, i told you that i am doing
a survey, you was not supposed to report my request but don't accept that
Thank you

**Pull request closed without merging**
