### PR TITLE
Remove confusing and unused upgrade.php

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | When all files have been migrated from the core to this repository, a file `upgrade.php` should have been deleted. It is a duplicate from cli-upgrade.php and does not run an upgrade as intended. For instance, `PS_VERSION_DB` was only updated if the previous SQL requests have worked.
| Type?             | bug fix
| BC breaks?        | Yes, one file is deleted
| Deprecations?     | Nope
| Fixed ticket?     | /
| Sponsor company   | @PrestaShopCorp
| How to test?      | Additional testing is not requested, as the CLI should run via another endpoint.

### CODE REVIEW

**Review by Hlavtox — APPROVED** [review]

**Comment by Hlavtox** [comment]
One question though - this file should be the one used for manual upgrade using browser, shouldn't we fix it instead? 🤔 
https://devdocs.prestashop-project.org/8/basics/keeping-up-to-date/upgrade/#database-upgrade

**Comment by ga-devfront** [comment]
> One question though - this file should be the one used for manual upgrade using browser, shouldn't we fix it instead? 🤔 https://devdocs.prestashop-project.org/8/basics/keeping-up-to-date/upgrade/#database-upgrade

I think we have to update documentation because we don't need to use `upgrade/upgrade.php` but [blob/dev/cli-upgrade.php](https://github.com/PrestaShop/autoupgrade/blob/dev/cli-upgrade.php) instead. Tel me if I'm wrong.

**Review by ga-devfront — APPROVED** [review]

**Review by M0rgan01 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
[Related PR opened in docs repository](https://github.com/PrestaShop/docs/pull/1797).

**Comment by Quetzacoalt91** [comment]
I allow myself to merge this PR, as this does not require a check from the QA team. Thanks for your reviews.

**Pull request merged**
