### PR TITLE
fix local module upgrade

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Fix local module upgrade mechanism (and improve performance by only checking if the zip exist for modules we want to upgrade locally instead of checking the existence of a zip for all modules that will be upgraded)
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| Sponsor company   | PrestaShop SA
| How to test?      | Put the zip of a module in admin/autoupgrade/modules, it should be of a version superior to the version currently installed. Do a prestashop upgrade, check that the module has been upgraded according to your zip

### CODE REVIEW

**Comment by matthieu-rolland** [comment]
CI is not happy, about some code too modern that I wrote, I'll deal with this 👍

**Review by sowbiba — DISMISSED** [review]
Nice 🚀

**Review by aniszr — DISMISSED** [review]
Hello @matthieu-rolland 

I tested the PR behavior when upgrading the store from PS 8.0.5 to PS 8.1.1 using the PR Autoupgrade :

- I used Product Comments module v 5.0.3 installed in the store 
- I added Product Comments module v6.0.2 in /admin/modules

The upgrade process from 8.0.5 to 8.1.1 went well :heavy_check_mark: 
The Product Comments module is upgraded to the v6.0.2 :heavy_check_mark: 

See attached screenrecord:

https://github.com/PrestaShop/autoupgrade/assets/92626242/93f209bc-2590-45e4-b90e-134cc0da35e8

QA :heavy_check_mark: 

Thanks!

**Review by kpodemski — DISMISSED** [review]
Sorry @matthieu-rolland 

It's QA approved but PHPCS Fixer is red :/

**Comment by kpodemski** [comment]
@matthieu-rolland @PrestaShop/qa-functional can we agree to send a commit with php cs fixer and if CI is green to merge this?

**Comment by Robin-Fischer-PS** [comment]
@kpodemski Yep, your suggestion suits me fine (if Matthieu is OK!) :)

**Review by kpodemski — APPROVED** [review]

**Pull request merged**
