### PR TITLE
Release 4.15.0

### PR DESCRIPTION
**Pull request by matthieu-rolland**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | release PR for autoupgrade 4.15
| How to test?      | this is release PR

### CODE REVIEW

**Review by nicosomb — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @matthieu-rolland 

@florine2623 and me have checked this PR. Here is our feedback : 

**Upgrade to 8.0.0 : NOK** :x:  
-Upgrade from 1778 to 8.0.0 with php 7.3 and php 7.2 : NOK
-Rollback from 8.0.0 to 1778 : OK
-Upgrade from 1788 to 8.0.0 with php 7.4 : NOK
-Rollback from 8.0.0 to 1788 : OK

image

https://user-images.githubusercontent.com/92912932/207808842-7dd22473-686b-4cd0-a969-e2075aabdf90.mp4



**Upgrade to 8.0.x created release : NOK** :x:  
-Upgrade from 1778 to 8.0.1 (release of 8.0.x fresh install) with php 7.3 and 7.2 : NOK
-Rollback from 8.0.1 to 1778 : OK
-Upgrade from 1788 to 8.0.1 (release of 8.0.x fresh install) with php 7.4 : NOK
-Rollback from 8.0.1 to 1788 : OK

image

https://user-images.githubusercontent.com/92912932/207638160-94b57353-687e-45d2-a1ce-282090eb5019.mp4


**Upgrade to develop created release : NOK with all broken BO with a 500 error**  :x: 
-Upgrade from 1778 to 8.0.0 to 8.1.0 (release of develop fresh install) php 7.3 and php 7.2 : NOK
-Upgrade from 1778 to 8.1.0 (release of develop fresh install) with php 7.3 and 7.2 : NOK
-Rollback from 8.1.0 to 1778 : OK
-Upgrade from 1788 to 8.1.0 (release of develop fresh install) with php 7.4 : NOK
-Rollback from 8.1.0 to 1788 : OK

image
image
image

https://user-images.githubusercontent.com/92912932/207637636-07ba1a29-fc39-4d4a-9451-d95ec2be265f.mp4

Could you please chek it ?

Thank You

**Comment by MatShir** [comment]
Does the upgrade work without mbo module ?

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @MatShir 

I have checked the upgrade from **1778 to 8.0.0** when uninstalling the `ps_mbo` module. 
The upgrade is passed but there is a 500 error in the console with this exception!


https://user-images.githubusercontent.com/92912932/208059940-41f71ac8-9fd3-4198-9b94-230374309c43.mp4


image

Thank You!

**Comment by MatShir** [comment]
It seems the upgrade went well, is the BO working well ? 
The error is normal, it says to the merchant to log again if you click on another link in the back office you will be redirected to the login.

**Comment by MatShir** [comment]
Here we need to check if you are well redirected to the login page, if so we need to test the same scenarios with mbo and the feature disable the module on.

**Comment by kpodemski** [comment]
This error with notifications is not really an error. Ideally, we should block notifications from being retrieved during the upgrade. It's normal that this feature doesn't work if the module is moving files, etc., etc.

**Comment by intraordinaire** [comment]
Hello there,

We indeed spotted a bug on our 4.1.1 version.
We fixed it on the 4.2.0 version, which is not released yet.

As it has a big impact here, we are releasing a [4.1.2 hotfix](https://github.com/PrestaShopCorp/ps_mbo/releases/tag/v4.1.2) version today.

Sorry for the inconvenience 😬

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @MatShir 

The BO seems to not be broken after the upgrade whatever when the `ps_mbo` module is installed or uninstalled.
But for the upgrade from **1778 / 1788 to 8.1.0,** there is another error which is not related to `mbo` and all BO is broken with this exception.

image

https://user-images.githubusercontent.com/92912932/208082360-de2633cc-b485-483a-bccf-dadd6f7727b0.mp4

This is the error when upgrading : 

`[INTERNAL] /var/www/html/Release_4.15_PR535/prestashop_1.7.7.8_new_/modules/ps_mbo/ps_mbo.php line 292 - Error: Call to a member function get() on null #0 /var/www/html/Release_4.15_PR535/prestashop_1.7.7.8_new_/modules/ps_mbo/src/Traits/HaveTabs.php(221): ps_mbo->get('prestashop.core...') #1 /var/www/html/Release_4.15_PR535/prestashop_1.7.7.8_new_/modules/ps_mbo/upgrade/upgrade-4.1.0.php(34): ps_mbo->updateTabs() #2 /var/www/html/Release_4.15_PR535/prestashop_1.7.7.8_new_/classes/module/Module.php(590): upgrade_module_4_1_0(Object(ps_mbo)) #3 /var/www/html/Release_4.15_PR535/prestashop_1.7.7.8_new_/modules/autoupgrade/classes/UpgradeTools/ModuleAdapter.php(249): ModuleCore->runUpgradeModule() #4 /var/www/html/Release_4.15_PR535/prestashop_1.7.7.8_new_/modules/autoupgrade/classes/UpgradeTools/ModuleAdapter.php(228): PrestaShop\Module\AutoUpgrade\UpgradeTools\ModuleAdapter->doUpgradeModule('ps_mbo') #5 /var/www/html/Release_4.15_PR535/prestashop_1.7.7.8_new_/modules/autoupgrade/classes/TaskRunner/Upgrade/UpgradeModules.php(65): PrestaShop\Module\AutoUpgrade\UpgradeTools\ModuleAdapter->upgradeModule(39574, 'ps_mbo') #6 /var/www/html/Release_4.15_PR535/prestashop_1.7.7.8_new_/admin-dev/autoupgrade/ajax-upgradetab.php(53): PrestaShop\Module\AutoUpgrade\TaskRunner\Upgrade\UpgradeModules->run() #7 {main}`


What do you think in this case of upgrade?

**Comment by HanaRebaiQA** [comment]
Hello,

Can I change the label to Waiting for QA ?

**Comment by MatShir** [comment]
👍

**Review by HanaRebaiQA — COMMENTED** [review]
Hello @MatShir 

Following the fix of the `ps_mbo` module, @AureRita and me did a test with this fix and we encountered always this problem when : 

- Upgrade from 1778 to 8.0.0
- Upgrade from 1788 to 8.0.0

1. An error is displayed when upgrading from 1778 and 1788 to 8.0

image

image

2. The `upgrade` option of the module is not displayed on 1778 and 1788, only on 8.0.0

https://user-images.githubusercontent.com/92912932/208392214-50c15443-10c4-4812-a16a-b87ec89f1baa.mp4

4. After the upgrade, the `Theme catalog `page should not be displayed on 8.0.0


image


What do you think in this case? We continue testing with the mbo module? Or should we only verify without it (when the module is uninstalled) ?

Thank You!

**Comment by AureRita** [comment]
There is the result of our test : 

By **Hana** : 

-Check the upgrade from 1778 to 8.0.0 with php 7.3 (BO and FO): OK :heavy_check_mark: 
-Check the rollback from 8.0.0 to 1778 with php 7.3  : OK :heavy_check_mark: 
-Check the upgrade from 1778 to 8.0.1 (release of 8.0.x) with php 7.3 (BO and FO): OK :heavy_check_mark: 
-Check the rollback from 8.0.1 (release of 8.0.x) to 1778 with php 7.3: OK :heavy_check_mark: 

Issue still there : 
https://github.com/PrestaShop/PrestaShop/issues/29700
and 
https://github.com/PrestaShop/PrestaShop/issues/29699

By **Aurelien** : 

PR tested and validated : 
https://github.com/PrestaShop/autoupgrade/pull/508   https://github.com/PrestaShop/autoupgrade/pull/510     https://github.com/PrestaShop/autoupgrade/pull/514   https://github.com/PrestaShop/autoupgrade/pull/511    https://github.com/PrestaShop/autoupgrade/pull/495   https://github.com/PrestaShop/autoupgrade/pull/497   https://github.com/PrestaShop/autoupgrade/pull/457   https://github.com/PrestaShop/autoupgrade/pull/505    https://github.com/PrestaShop/autoupgrade/pull/466   https://github.com/PrestaShop/autoupgrade/pull/441 
  https://github.com/PrestaShop/autoupgrade/pull/489   https://github.com/PrestaShop/autoupgrade/pull/487   https://github.com/PrestaShop/autoupgrade/pull/491
https://github.com/PrestaShop/autoupgrade/pull/458
https://github.com/PrestaShop/autoupgrade/pull/450
https://github.com/PrestaShop/autoupgrade/pull/469
https://github.com/PrestaShop/autoupgrade/pull/440
https://github.com/PrestaShop/autoupgrade/pull/421
https://github.com/PrestaShop/autoupgrade/pull/464
https://github.com/PrestaShop/autoupgrade/pull/422

PR not tested because it's an autoupgrade on develop and we want to prioritize the upgrade on 8.0.0 : 

https://github.com/PrestaShop/autoupgrade/pull/526
https://github.com/PrestaShop/autoupgrade/pull/527
https://github.com/PrestaShop/autoupgrade/pull/507

PR where it does not seem to be fully installed : 

https://github.com/PrestaShop/autoupgrade/pull/484
-> If we uninstall the module before an update, after it the files is created but not installed in prestashop ( We think in the expected behavior it should be installed ) ( for me, it not block the PR, because it's partially installed )

What we have after the update : 
image

@MatShir is it the expected behavior or not ? 

After that day, I tested again to update with the MBO module and it works, as we can see here : 

image

**To Conclude :** 

We have only a minor issue, we didn't blocked this release for this, I will create an issue if it's important for you,

It's QA :heavy_check_mark:

**Review by AureRita — DISMISSED** [review]

**Review by kpodemski — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
Thank you everyone involved in building and testing this module release

**Pull request merged**
