### PR TITLE
Release 4.16.0

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Release version 4.16.0, mainly to mitigate the problems with sessions.
| Type?             | 
| BC breaks?        | 
| Deprecations?     | 
| Fixed ticket?     | 
| Sponsor company   | 
| How to test?      |

### CODE REVIEW

**Comment by Hlavtox** [comment]
Ping @kpodemski for Waiting for QA

**Review by nicosomb — APPROVED** [review]

**Comment by Hlavtox** [comment]
@kpodemski Why is this blocked? Can't we put out the patch version?

**Comment by kpodemski** [comment]
@Hlavtox 

I don't expect a non-technical person to click the upgrade to PrestaShop 8.0, the workaround for the sessions is super easy. I think it would be better to let QA test the 8.0.2, and then focus on the 8.1 compatible version (4.16). Wdyt?

**Comment by matthieu-rolland** [comment]
I think this PR can be unblocked no ? @kpodemski 

So that the QA team can test upgrades to 8.1 from a proper release instead of working from the dev branch

**Pull request closed without merging**
