### PR TITLE
Rename 8.1.4.sql to 8.1.5.sql

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Following a postpone of a version with changes, we rename an upgrade file.
| Type?             | 
| BC breaks?        | 
| Deprecations?     | 
| Fixed ticket?     | 
| Sponsor company   | 
| How to test?      |

### CODE REVIEW

**Comment by Hlavtox** [comment]
Ping @matks

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
As this is a basic renaming following transformation of milestone 8.1.4 to 8.1.5 I believe it can be merged like this, we simply do this in order to mirror the change done on the milestone

**Comment by matks** [comment]
```
Error: The operation was canceled.
```

🤔

**Comment by matks** [comment]
Re-running

**Review by jolelievre — APPROVED** [review]

**Pull request merged**
