### PR TITLE
Add actionAdminMenuTabsModifier hook

### PR DESCRIPTION
**Pull request by cvng**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Adds a new hook added in https://github.com/PrestaShop/PrestaShop/pull/31691
| Type?             | new feature
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     |
| Sponsor company   |
| How to test?      | see if the hook is in the upgraded version

### CODE REVIEW

**Review by Hlavtox — APPROVED** [review]

**Review by kpodemski — APPROVED** [review]

**Comment by HanaRebaiQA** [comment]
Hello @cvng 

First of all Thanks for your PR! But, I think that the PR of the PS Core [#31691](https://github.com/PrestaShop/PrestaShop/pull/31691) which will contain the new hook should be validated and merged before testing this related PR of the autoupgrade.

@kpodemski What do you think ?

**Comment by kpodemski** [comment]
@HanaRebaiQA yes, of course, PR has to be tested first

**Comment by okom3pom** [comment]
https://github.com/PrestaShop/PrestaShop/pull/31691 merged

You can remove blocked validate the PR, and make a new version of the module to not break the install and normally this PR should not have been blocked but tested on an update and not on a new installation.

@cvng Could you please edit the How to test

**Comment by kpodemski** [comment]
Hi @okom3pom 
We wait with such PRs for the original PR to be merged first, then we approve this change, and we only see whether the hook exists in the database or not for upgraded installation. Committers and QA agreed that QA wouldn't be included in the testing of adding new hooks, it can be tested by a dev 👍🏻 I hope it answers your concerns.

**Review by jolelievre — APPROVED** [review]
Thanks @cvng

**Comment by kpodemski** [comment]
tested & merged, thanks @cvng :)

**Comment by cvng** [comment]
@jolelievre @kpodemski thanks for the support :)

**Pull request merged**
