### PR TITLE
Add actionPDFInvoiceRender

### LINKED ISSUE #36741: Hook actionPDFInvoiceRender is missing from installation
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hook 'actionPDFInvoiceRender' is missing from the database in fresh PS installs.
It is, however, referenced multiple times in the core :
classes\order\OrderHistory.php
classes\PaymentModule.php
controllers\admin\AdminPdfController.php
controllers\front\PdfInvoiceController.php
src\Adapter\PDF\InvoicePdfGenerator.php
src\Adapter\PDF\OrderInvoicePdfGenerator.php

### Expected behavior

The hook should be installed in the ps_hook table so that modules can properly be attached to it.

### Steps to reproduce

1. Install a new instance of Prestashop
2. Search for actionPDFInvoiceRender in the ps_hook table

### PrestaShop version(s) where the bug happened

8.1.7

### PHP version(s) where the bug happened

8.1.29

### If your bug is related to a module, specify its name and its version

_No response_

### Your company or customer's name goes here (if applicable).

Adipso

### PR DESCRIPTION
**Pull request by Touxten**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Add actionPDFInvoiceRender
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/36741
| Sponsor company   | @Touxten 

This PR completes https://github.com/PrestaShop/PrestaShop/pull/36742 can you relaunch test on it

### CODE REVIEW

**Review by Hlavtox — APPROVED** [review]

**Comment by kpodemski** [comment]
@PrestaShop/qa-functional 

new hook entry follow the required format, so I think there's no need for a functional QA, please confirm :)

**Comment by ga-devfront** [comment]
@kpodemski you are right. I just blocked the PR until the PR on the core is merged.

**Comment by Robin-Fischer-PS** [comment]
Hi, no functional QA needed, indeed. Thanks!

**Comment by kpodemski** [comment]
thank you @Touxten

**Pull request merged**
