### PR TITLE
Add category additional description column during upgrade

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Adds database column for related change - https://github.com/PrestaShop/PrestaShop/pull/27292
| Type?             | new feature
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | -
| How to test?      | To be tested at the same time as PrestaShop/PrestaShop#27292
| Possible impacts? | -

### CODE REVIEW

**Review by saulaski — DISMISSED** [review]

**Review by atomiix — APPROVED** [review]

**Comment by khouloudbelguith** [comment]
Hi @Hlavtox,

Could you please check the Conflicting files?

Thanks!

**Comment by Hlavtox** [comment]
@khouloudbelguith Rebased

**Review by khouloudbelguith — COMMENTED** [review]
Hi @Hlavtox,

I checked those upgrades:

- From PS1770 to your PR: https://github.com/PrestaShop/PrestaShop/pull/27292 => ok
- From PS1778 to your PR: https://github.com/PrestaShop/PrestaShop/pull/27292 => ok
- From PS1785 to your PR: https://github.com/PrestaShop/PrestaShop/pull/27292 => ok

https://user-images.githubusercontent.com/16067358/161937339-ca233377-9a81-4320-a4a1-69e06b49ac12.mp4

PS: Before the upgrade, I uninstalled those modules:

- mbo
- welcome
- ps_facebook
- ps_checkout
- ps_metrics

Also, in the autoupgrade module, those options `Switch to the default theme` & `Disable all overrides` are disabled in my case.
Because if those options are enabled, I have an error during the upgrade, but not related to this PR (I manage to reproduce the error with an upgrade from PS1770 to PS8.0.0:develop using the dev branch of the autoupgrade module) => I will create a new issue.

Thanks!

**Comment by Hlavtox** [comment]
Awesomeeeee!!!! Thank you @khouloudbelguith 🎉

**Comment by Progi1984** [comment]
Thanks @Hlavtox & @khouloudbelguith

**Pull request merged**
