### PR TITLE
Hook for alternative search panel

### PR DESCRIPTION
**Pull request by sowbiba**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Add hook actionGetAlternativeSearchPanels for 8.0 upgrade
| Type?             | new feature
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | -

Related to https://github.com/PrestaShop/PrestaShop/pull/28504

### CODE REVIEW

**Review by matks — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Comment by sLorenzini** [comment]
Hello @sowbiba and @PrestaShop/prestashop-core-developers,
 
This PR is blocked by this issue https://github.com/PrestaShop/PrestaShop/issues/28555 to allow creation of a release. Could you please remove the "blocked" label when this issue is fixed ? Thanks !

**Review by sLorenzini — APPROVED** [review]
hello @sowbiba,

Tested on upgrade from 1.7.7.8 to 8.0.0
PHP version 7.2

'actionGetAlternativeSearchPanels' hook is displayed and available.

QA approved ✅

**Comment by Progi1984** [comment]
@sLorenzini We are waiting for that https://github.com/PrestaShop/PrestaShop/pull/28504 is merged.

**Review by jolelievre — APPROVED** [review]
Thanks @sowbiba

**Review by sLorenzini — APPROVED** [review]
hi @sowbiba,

I've retested this PR with new fresh install with upgrade from 1.7.7.8 to 8.0.0
PHP version 7.2

'actionGetAlternativeSearchPanels' hook is displayed and available.

QA approved ✅

Thanks

**Comment by Progi1984** [comment]
Thanks @sowbiba & @sLorenzini

**Pull request merged**
