### PR TITLE
UI Tests - Add V9 to upgrade in local archive

### PR DESCRIPTION
**Pull request by AureRita**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Add V9 to Upgrade in local archive into the sanity 
| Type?             | improvement
| BC breaks?        |  no
| Deprecations?     | no
| Fixed ticket?     | 
| Sponsor company   | PrestaShop Core
| How to test?      | CI is green

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hello @AureRita!

This is your first pull request on [autoupgrade](https://github.com/PrestaShop/autoupgrade/) repository of the PrestaShop project.

Thank you, and welcome to this Open Source community!

**Comment by M0rgan01** [comment]
This won't work at the moment. V9 must be present in the list here https://github.com/PrestaShop/zip-archives and also present in the API -> https://api.prestashop.com/xml/md5/9.0.0.xml

**Comment by matks** [comment]
> This won't work at the moment. V9 must be present in the list here https://github.com/PrestaShop/zip-archives

Eeeeeeuh I created https://github.com/PrestaShop/zip-archives to be used as a library where anyone can find past ZIP of PrestaShop. Did you guys use it for something else? 😅

**Comment by M0rgan01** [comment]
@matks we use this repository for **testing** purposes, more precisely for the local channel. This contains the vast majority of the archives, more than in the releases of the official repository where it has happened on several occasions that certain zips are missing.

**Review by M0rgan01 — APPROVED** [review]

**Review by nesrineabdmouleh — APPROVED** [review]

**Pull request merged**
