### PR TITLE
Fix issue with bad table prefix

### PR DESCRIPTION
**Pull request by Prestaworks**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | I changed the prefix in the SQL query, so the extra underscore was removed.
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #31219 https://github.com/PrestaShop/PrestaShop/issues/31219 
| Sponsor company   | Prestaworks AB
| How to test?      | Follow instruction in issue

### CODE REVIEW

**Review by Hlavtox — APPROVED** [review]

**Comment by Hlavtox** [comment]
Just to be sure, I checked https://github.com/PrestaShop/PrestaShop/blob/1.5.0.0/install-dev/sql/db.sql if it was not due to some old typo, but all good. ✅

**Comment by paulnoelcholot** [comment]
Hi @Prestaworks @Hlavtox,

I added the Blocked label because the issues have not been verified by the QA team.
As soon as the "Verified" label has been applied by the QA on this issue, we will test this PR.

Thanks!

**Comment by AureRita** [comment]
Hi @Prestaworks 

as said in this comment https://github.com/PrestaShop/PrestaShop/issues/31219#issuecomment-1432316736 
this one will be tested by a dev, ping @PrestaShop/prestashop-core-developers 

Thanks

**Comment by nicosomb** [comment]
I wanted to try your PR but I have same issue than https://github.com/PrestaShop/PrestaShop/issues/30761

**Comment by jocel1** [comment]
I confirm this change is definitely needed

**Review by kpodemski — APPROVED** [review]

**Comment by kpodemski** [comment]
thank you @Prestaworks !

**Pull request merged**
