### PR TITLE
Rename function name to avoid conflicts while upgrading several modules in a row

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
Following the feedback on the forum: https://www.prestashop.com/forums/topic/1023519-fatal-error-module-file/

### CODE REVIEW

**Review by Matt75 — APPROVED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by PierreRambaud** [comment]
Good to know that we can't update to modules containing upgrade functions with the same version :joy:

**Comment by Quetzacoalt91** [comment]
yeah we figured that out at the same time :o 

Before merging this PR, line 43 should be modified. Can you please it as "Changes required"?

**Review by Matt75 — CHANGES_REQUESTED** [review]
Line 43 `removeFromFsDuringUpgrade(iterator_to_array($iterator));` should be replaced by `removeAutoupgradePhpUnitFromFsDuringUpgrade(iterator_to_array($iterator));`

**Review by Progi1984 — DISMISSED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Review by Progi1984 — DISMISSED** [review]

**Comment by Progi1984** [comment]
@Quetzacoalt91 Multiples relaunch for Travis but it seems that you have a problem. I try close/open.

**Review by Matt75 — DISMISSED** [review]

**Comment by Quetzacoalt91** [comment]
PR has been rebased

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by PierreRambaud** [comment]
Thank you @Quetzacoalt91

**Pull request merged**
