### PR TITLE
Add 410 http code to redirect_type column

### PR DESCRIPTION
**Pull request by jf-viguier**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Add 410 http code to redirect_type column
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/27413
| How to test?      | See other PR in Core
| Possible impacts? | none

### CODE REVIEW

**Review by PierreRambaud — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Review by PululuK — APPROVED** [review]
Waiting for https://github.com/PrestaShop/PrestaShop/pull/27467

**Comment by jf-viguier** [comment]
@hibatallahAouadni For testing, you have to launch this sql manually from https://github.com/PrestaShop/autoupgrade/pull/456/files :
```
ALTER TABLE `ps_product` MODIFY COLUMN `redirect_type` ENUM(
    '404', '410', '301-product', '302-product', '301-category', '302-category'
) NOT NULL DEFAULT '404';
ALTER TABLE `ps_product_shop` MODIFY COLUMN `redirect_type` ENUM(
    '404', '410', '301-product', '302-product', '301-category', '302-category'
) NOT NULL DEFAULT '404';
```
I've replaced PREFIX_ by standard prefix ps_

**Comment by Progi1984** [comment]
I merge it as https://github.com/PrestaShop/PrestaShop/pull/27467 is merged.

**Comment by hibatallahAouadni** [comment]
Hello everyone,

The only issue I encountred with this PR is due to this issue https://github.com/PrestaShop/PrestaShop/issues/26503
So, LGTM, QA :heavy_check_mark:

image

As you can see the new redirect type 410 is well added in the product & product_shop tables :tada: 

Thanks!

**Pull request merged**
