### PR TITLE
Fix tab wordings

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Fixes security tabs wordings for people that started on 8.0.0-8.1.1
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/33763
| Sponsor company   | 
| How to test?      | Install 8.0.0, upgrade to 8.1.2 and follow steps in this issue - https://github.com/PrestaShop/PrestaShop/issues/33763

### CODE REVIEW

**Comment by Hlavtox** [comment]
Ping @nicosomb @florine2623

**Review by nicosomb — APPROVED** [review]

**Review by florine2623 — APPROVED** [review]
Hello @Hlavtox ,

I followed these steps :
- Install PS 8.0.0
- Run this in phpmyadmin: `UPDATE ps_tab_lang SET name = 'Blabla';`
- Install autoupgrade module `v4.16.2`
- Install autoupgrade PR #619 
- Upgrade to 8.1.2 with local archive (using latest branch `8.1.x` and run `php CreateRelease.php --version 8.1.2`)
- Install / Update the language you are currently using in backoffice.
- See result

Upgrade successful (but not to 8.1.2, it upgraded to 8.1.1)

Screenshot 2023-09-01 at 14 38 07

It is QA ✅ 
Thanks!

**Comment by Hlavtox** [comment]
You are awesome! So this one is solved. 🎉 Now we just need to remember to release autoupgrade before 8.1.2 is finished. :-)

**Comment by kpodemski** [comment]
thanks @Hlavtox :)

**Pull request merged**
