### PR TITLE
Add and update feature flags 

### LINKED ISSUE #35727: Autoupgrade - Don't have the experimental feature on autoupgrade
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

When I do an upgrade 8.0.5 from to 8.1.5, I don't have the experimental feature as we have with a fresh version of 8.1.5 as you can see : 

[recording(150).webm](https://github.com/PrestaShop/PrestaShop/assets/100699445/1dcfae17-ce55-42b3-91bc-95db241ddfae)

### Expected behavior

I wish I could Find all the experimental feature as you can see here : 
image

### Steps to reproduce

1. Go to BO 
2. Go to module manager
3. install Autoupgrade
4. Do an upgrade on 8.1.5 from major release 
5. Go to Bo > Advanced Parameters > Experimental Feature 

### PrestaShop version(s) where the bug happened

8.0.5

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

autoupgrade v5.0.1

### Your company or customer's name goes here (if applicable).

PS

### LINKED ISSUE #35748: Autoupgrade - When you upgrade on V9.0, you'll have a feature flag doesn't exist
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello, when I upgrade from 8.1.5 or 8.0.5 to V9.0.0, I have an Error 500 aboput the feature flag 

image

### Expected behavior

I wish I could use my shop v9.0

### Steps to reproduce

1. Install a fresh install of 8.1.5 
2. Download an autoupgrade from dev version of presta
3. do an upgrade from a folder 
4. Launch the upgrade 
5. :negative_squared_cross_mark: you'll have the 500 error 

### PrestaShop version(s) where the bug happened

8.0.5 and 8.1.5 to develop

### PHP version(s) where the bug happened

8.1

### If your bug is related to a module, specify its name and its version

autoupgrade v5.0.1 - dev mode

### Your company or customer's name goes here (if applicable).

PS

### PR DESCRIPTION
**Pull request by ga-devfront**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | completes the omissions of feature flag changes in versions 8.1.x and 9.x
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/autoupgrade/pull/679#issuecomment-2020335426 , Fixes https://github.com/PrestaShop/PrestaShop/issues/35748, Fixes https://github.com/PrestaShop/PrestaShop/issues/35727 , Fixes https://github.com/PrestaShop/autoupgrade/pull/615
| Sponsor company   | @PrestaShopCorp
| How to test?      | Try to upgrade from 8.0.x to 8.1.x or with zip of 9.x

### CODE REVIEW

**Comment by ga-devfront** [comment]
I'm reverting the PR to WIP because I realized that there was a lot of missing features in all versions.

**Comment by ga-devfront** [comment]
The PR is up-to-date, I did a global review from version 1.7.8.x to 9.x (tag by tag) to check all feature flag modifications. There were a lot of omissions on 8.1.x as well as on 9.x. The PR is ready to be reviewed and tested!

**Review by jolelievre — APPROVED** [review]

**Comment by AureRita** [comment]
Hi @ga-devfront 

Thank you for your PR ! This correct the issue on Experimented Feature and we can do an upgrade from 
8.0.5 -> 8.1.5 -> 9.0.0 
8.0.5 -> 9.0.0 

But currently when we want to upgrade from 

1.7.8.11 to 8.1.5 (with release major) it works and if just after that, if you do the upgrade from 8.1.5 to 9.0.0 (with files) we have this issue : 
image

Because this issue doesn't seems to be related of your PR, It's a QA :heavy_check_mark: 

and I'll create a new issue

**Review by M0rgan01 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Related to:
* https://github.com/PrestaShop/PrestaShop/pull/34172

**Pull request merged**
