### PR TITLE
Fix translations

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | This is not translatable into other languages, creates nonsense strings. :-))) Proper plurals must be done by ICU. Unfortunately, not working in PrestaShop.
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Crowdin
| Sponsor company   | 
| How to test?      | No need to test.

### CODE REVIEW

**Review by Quetzacoalt91 — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Let's keep it simple indeed

**Comment by Hlavtox** [comment]
@Quetzacoalt91 A partially-working solution would be to create two different strings, if there is 1 or more. That would be translatable.

But still not an ideal solution, it would work in English and Czech, but maybe other languages would have different plural forms for 2,3,4,5 etc. items.

**Comment by Quetzacoalt91** [comment]
Yeah I've dealt with this topic on other projects by providing the different versions in a single string, each version separated by a pipe.
For instance: `I have no apples|I have 1 apple|I have %d apples`.

But it was possible if the translator was able to find the proper part to use, depending on the target language and the parameters, and this is not the case here. (yet). :/

**Review by M0rgan01 — APPROVED** [review]

**Comment by ps-jarvis** [comment]
PR merged, well done!

Message to @PrestaShop/committers: do not forget to milestone it before the merge.

**Pull request merged**
