### PR TITLE
Removing patch version when comparing php version for destination version

### PR DESCRIPTION
**Pull request by M0rgan01**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Removing patch version when comparing php version for destination version
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | -
| Sponsor company   | -
| How to test?      | try to update to Prestashop 8.1.7 (php requirement 7.2.5) with php 7.2.1x

### CODE REVIEW

**Comment by M0rgan01** [comment]
Hi @jf-viguier ! This should help with the PHP version comparison bug.

**Review by ga-devfront — APPROVED** [review]

**Comment by Quetzacoalt91** [comment]
Work in progress while some tests are added.

**Comment by Hlavtox** [comment]
Why don't you just use version_compare? :D

**Review by Quetzacoalt91 — APPROVED** [review]

**Review by AureRita — APPROVED** [review]
Hi @M0rgan01 

Thank you for your PR, I tested it and it seems to works as you can see : 

[recording(285).webm](https://github.com/user-attachments/assets/0961f815-9706-41b3-a195-de58cc4bb277)

Tested from : 
1.7.7.8 to 8.1.7 
8.0.4 to 8.1.7 
8.1.5 to 8.1.7 
8.1.7 to 9.0.0
8.1.5 to 9.0.0
8.0.5 to 9.0.0

Because the PR seems to works as expected, It's QA :heavy_check_mark: 

Thank you

**Pull request merged**
