### PR TITLE
Fix note column creation in Orders table

### LINKED ISSUE #37224: Autoupgrade - A 500 internal server error when confirm order in any shop upgraded from  1.7.7 or 1.7.6 to 1.7.8.11 and 8.2.0
### Prerequisites

- [X] I understand and accept the project's [code of conduct](https://github.com/PrestaShop/PrestaShop/blob/develop/CODE_OF_CONDUCT.md).
- [X] I have already [searched in existing issues](https://github.com/PrestaShop/PrestaShop/issues?q=is%3Aissue+label%3ABug) and found no previous report of this bug.

### Describe the bug and add attachments

Hello,
A 500 internal server error when confirm order in any shop upgraded from  1.7.7 or 1.7.6 to 1.7.8.11 and 8.2.0
and an error when edit the quantity of product in order page

https://www.awesomescreenshot.com/video/32819214?key=5811fb59e19580dc6a5ca8f5b6d00537

Image

Image

### Expected behavior

No error

### Steps to reproduce

1- Install 1.7.7.0
2- Upgrade to 8.2.0 or 1.7.8.11
3- Login and go to Orders page
4- Go to the first order and edit product quantity
5- See the error
6- Go to FO and create an order
7- See the error

### PrestaShop version(s) where the bug happened

8.2.0 or 1.7.8.11

### PHP version(s) where the bug happened

7.1 - 7.2 - 7.3

### If your bug is related to a module, specify its name and its version

autoupgrade 

### Your company or customer's name goes here (if applicable).

_No response_

### PR DESCRIPTION
**Pull request by M0rgan01**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Fix note column creation in Orders table
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/37224
| Sponsor company   |-
| How to test?      | -

### CODE REVIEW

**Comment by Hlavtox** [comment]
Ahhhh, it was me who broke it then. In https://github.com/PrestaShop/autoupgrade/pull/853#pullrequestreview-2315692934, and @AureRita actually found this bug, but marked it QA ✅, and I merged it. :D

I think there is no need to catchup because 7.0.0 was not yet released, so nobody has ran the broken code. Or?

**Comment by Hlavtox** [comment]
Btw @M0rgan01 & @Quetzacoalt91, will the upgrade log say KO if we add a return here? 

https://github.com/Hlavtox/autoupgrade/blob/dev/upgrade/php/add_column.php

(and all of the PHP scripts)

**Comment by M0rgan01** [comment]
@Hlavtox 

> I think there is no need to catchup because 7.0.0 was not yet released, so nobody has ran the broken code. Or?

I remove it. I thought it was in production but no :D

> Btw @M0rgan01 & @Quetzacoalt91, will the upgrade log say KO if we add a return here?

Good question. I think we could implement better error handling for these scripts, because apparently it's level 0 here

**Comment by Quetzacoalt91** [comment]
> Btw @M0rgan01 & @Quetzacoalt91, will the upgrade log say KO if we add a return here?
> 
> https://github.com/Hlavtox/autoupgrade/blob/dev/upgrade/php/add_column.php
> 
> (and all of the PHP scripts)

Returning `false` marks the script as failed, so yes.

You can even return an array with an error message in it, that will be reported in the logger.

https://github.com/PrestaShop/autoupgrade/blob/0adfabb1e86cc4b92e8367ff278fb1e08bcb7a8a/classes/UpgradeTools/CoreUpgrader/CoreUpgrader.php#L474-L489

**Comment by Hlavtox** [comment]
Good! :-)

So, maybe we should check that we return a value from all of those php upgrade scripts, so we catch it.

**Review by ga-devfront — APPROVED** [review]

**Review by AureRita — APPROVED** [review]
Hi @M0rgan01 

Thank you for your PR, I tested it and it seems to works as you can see : 

[recording(311).webm](https://github.com/user-attachments/assets/c5ae71e4-7112-457e-b152-4d3880f3e7a9)


Tested from : 
1.7.7.5 to 1.7.8.11 
8.0.5 to 8.2  
8.2 to 9.0.0
8.0.5 to 9.0.0

Because the PR seems to works as expected, It's QA :heavy_check_mark: 

Thank you

**Pull request merged**
