### PR TITLE
Update 8.1.0.sql for actionProductPriceCalculation hook

### PR DESCRIPTION
**Pull request by jolelievre**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Added new hook to override price calculation
| Type?             | new feature
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Related to https://github.com/PrestaShop/PrestaShop/pull/27927
| How to test?      | Upgrade with the current branch the hook actionProductPriceCalculation should be present in the `hook` table
| Possible impacts? | ~

### CODE REVIEW

**Comment by matthieu-rolland** [comment]
the query is correct overall but @lartist gave some valid feedback, LGTM otherwise

**Comment by Hlavtox** [comment]
Unblocked, PR may need a rebase to work.

**Comment by Hlavtox** [comment]
@jolelievre Ping to finish it please. :-)

**Comment by Hlavtox** [comment]
@jolelievre Needs rebase and finishing, we need it for 8.1, please.

**Comment by jolelievre** [comment]
Handled by https://github.com/PrestaShop/autoupgrade/pull/573

**Pull request closed without merging**
