### PR TITLE
Clean old not existing modules in database for next major version PS 9.x

### PR DESCRIPTION
**Pull request by ShaiMagal**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | A lot of customers have in database tables "ps_modules" / "ps_hook_module" (and other similar tables) a lot of nonexistent modules on FTP. Then there will be this information in php error log - _PHP Deprecated:  The hook "XXX" is deprecated, please use "YYY" instead in module "ZZZ". in QQQ/classes/Hook.php on line 914_, so we should have resolved this discrepancy in the database to match the FTP content for major version PS 9.x, we would like to have this major version clean as much possible. For real examples check below. Most of problems(modules) are from old version PS 1.6 (it magically persist for unknown reasons)
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| Sponsor company   | https://www.openservis.cz/
| How to test?      | 

Real examples:
[12-Nov-2023 17:05:49 Europe/Prague] PHP Deprecated:  The hook "Header" is deprecated, please use "displayHeader" instead in module "blockbestsellers". in XXX/classes/Hook.php on line 914
[12-Nov-2023 17:05:49 Europe/Prague] PHP Deprecated:  The hook "Header" is deprecated, please use "displayHeader" instead in module "blockcontact". in XXX/classes/Hook.php on line 914
[12-Nov-2023 17:05:49 Europe/Prague] PHP Deprecated:  The hook "Header" is deprecated, please use "displayHeader" instead in module "blockcontactinfos". in XXX/classes/Hook.php on line 914
[12-Nov-2023 17:05:49 Europe/Prague] PHP Deprecated:  The hook "Header" is deprecated, please use "displayHeader" instead in module "blockmanufacturer". in XXX/classes/Hook.php on line 914
[12-Nov-2023 17:05:49 Europe/Prague] PHP Deprecated:  The hook "Header" is deprecated, please use "displayHeader" instead in module "blockmyaccount". in XXX/classes/Hook.php on line 914
[12-Nov-2023 17:05:49 Europe/Prague] PHP Deprecated:  The hook "Header" is deprecated, please use "displayHeader" instead in module "blockmyaccountfooter". in XXX/classes/Hook.php on line 914
[12-Nov-2023 17:05:49 Europe/Prague] PHP Deprecated:  The hook "Header" is deprecated, please use "displayHeader" instead in module "blocknewproducts". in XXX/classes/Hook.php on line 914
[12-Nov-2023 17:05:49 Europe/Prague] PHP Deprecated:  The hook "Header" is deprecated, please use "displayHeader" instead in module "blockpaymentlogo". in XXX/classes/Hook.php on line 914
[12-Nov-2023 17:05:49 Europe/Prague] PHP Deprecated:  The hook "Header" is deprecated, please use "displayHeader" instead in module "blockspecials". in XXX/classes/Hook.php on line 914
[12-Nov-2023 17:05:49 Europe/Prague] PHP Deprecated:  The hook "Header" is deprecated, please use "displayHeader" instead in module "blocksupplier". in XXX/classes/Hook.php on line 914
[12-Nov-2023 17:05:49 Europe/Prague] PHP Deprecated:  The hook "Header" is deprecated, please use "displayHeader" instead in module "blockviewed". in XXX/classes/Hook.php on line 914
[12-Nov-2023 17:05:49 Europe/Prague] PHP Deprecated:  The hook "Header" is deprecated, please use "displayHeader" instead in module "homeslider". in XXX/classes/Hook.php on line 914
[12-Nov-2023 17:05:49 Europe/Prague] PHP Deprecated:  The hook "Header" is deprecated, please use "displayHeader" instead in module "homefeatured". in XXX/classes/Hook.php on line 914
[12-Nov-2023 17:05:49 Europe/Prague] PHP Deprecated:  The hook "Header" is deprecated, please use "displayHeader" instead in module "themeconfigurator". in XXX/classes/Hook.php on line 914
[12-Nov-2023 17:05:49 Europe/Prague] PHP Deprecated:  The hook "Header" is deprecated, please use "displayHeader" instead in module "sendtoafriend". in XXX/classes/Hook.php on line 914
[12-Nov-2023 17:05:49 Europe/Prague] PHP Deprecated:  The hook "Header" is deprecated, please use "displayHeader" instead in module "blockpermanentlinks". in XXX/classes/Hook.php on line 914
[12-Nov-2023 17:05:49 Europe/Prague] PHP Deprecated:  The hook "Header" is deprecated, please use "displayHeader" instead in module "mailalerts". in XXX/classes/Hook.php on line 914
[12-Nov-2023 17:05:49 Europe/Prague] PHP Deprecated:  The hook "Header" is deprecated, please use "displayHeader" instead in module "productscategory". in XXX/classes/Hook.php on line 914
[12-Nov-2023 17:05:49 Europe/Prague] PHP Deprecated:  The hook "Header" is deprecated, please use "displayHeader" instead in module "ganalytics". in XXX/classes/Hook.php on line 914

### CODE REVIEW

**Comment by Seb33300** [comment]
IMO this should be added to the `cleanDatabase` step to be executed at every upgrade. Not only on 9.0 upgrade.

**Comment by ShaiMagal** [comment]
@Seb33300 I think one time cleaning for major version 9.x can be enough. It's not necessary to run after every minor update.

**Comment by ShaiMagal** [comment]
I think, this PR will have same problem like #650

**Review by M0rgan01 — COMMENTED** [review]
same conclusion as https://github.com/PrestaShop/autoupgrade/pull/650 ?

**Comment by matks** [comment]
@M0rgan01 Yes indeed.

[I am sure](https://github.com/PrestaShop/autoupgrade/pull/650#issuecomment-1914307091) we don't want this - at least not this way

**Pull request closed without merging**
