### PR TITLE
Avoid drop of some tables like guests

### PR DESCRIPTION
**Pull request by Quetzacoalt91**
| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Fix deletion of some tables by mistake
| Type?         | bug fix
| BC breaks?    | Nope
| Deprecations? | Nope
| Fixed ticket? | /
| How to test?  | Backup, upgrade then restore, the customer data must remain in DB

### CODE REVIEW

**Comment by matks** [comment]
2 GitHub Actions fail but I think it's weird items. There is a PHP5.6 GA build successfull. The other must be bad duplicates.

**Comment by Quetzacoalt91** [comment]
This seems to be related to GitHub hitself. 
image

Can you restart the workflow just in case?

**Comment by Progi1984** [comment]
@Quetzacoalt91 I restarted them this morning : same result.

**Comment by atomiix** [comment]
@Quetzacoalt91 isn't there something to do here too? https://github.com/PrestaShop/autoupgrade/blob/master/classes/TaskRunner/Upgrade/BackupDb.php#L110

**Comment by atomiix** [comment]
@Quetzacoalt91 I don't remember why I said that 😅
But I don't think it is useful add the `guest` table to the list of data to save.

**Review by atomiix — APPROVED** [review]

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by Progi1984** [comment]
Thanks @Quetzacoalt91 & @sarahdib

**Pull request merged**
