### PR TITLE
Add sitemap hook on upgrade

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Autoupgrade PR for https://github.com/PrestaShop/PrestaShop/pull/29797
| Type?             | new feature
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | 
| How to test?      | 
| Possible impacts? |

### CODE REVIEW

**Comment by Hlavtox** [comment]
@nicosomb I don't understand, it's just an autoupgrade PR with the same name 🤷‍♂️

**Comment by nicosomb** [comment]
@Hlavtox I asked you because I believed that you made some changes on frontend sitemap in this PR. But no problem ;-)

**Review by kpodemski — APPROVED** [review]

**Review by hibatallahAouadni — APPROVED** [review]
Hello @Hlavtox 

Thanks for your PR :rocket: 
Here's the steps how I test this PR:

1. install a shop 8.0.0 or 1.7.8.7 
2. `cd yourshop_1.7.8.7/modules`
3. `git clone https://github.com/PrestaShop/autoupgrade.git`
4. `cd autoupgrade`
5. `git prc origin 527 dev`
6. BO>module manager or module catalog>install autoupgrade 
7. create a release from develop branch, under a develop shop: `cd tools/build/`
8. `sudo php CreateRelease.php --version 8.1.0`
9. copy the release .zip and xml file from tools/build/releases 
10. paste these under admin-dev/autoupgrade/dowload
11. Now, back to your shop 1.7.8.7 or 8.0.0 
12. BO>Module Manager>Click on Configure of autoupgrade
13. Use these options to upgrade (see the attached screenshot below)
image
14. Click on Save
15. Then Upgrade
16. BO>Advanced Parameters>Database
17. Create this request: select * from ps_hook
18. Then view it => the hook is well registered (see the attached screenshot below)
19. image
LGTM, QA :heavy_check_mark: 

Thanks!

**Comment by jolelievre** [comment]
Thanks @Hlavtox and @hibatallahAouadni

**Pull request merged**
