### PR TITLE
Fix some license headers and add LICENSE file

### PR DESCRIPTION
**Pull request by matks**

### CODE REVIEW

**Comment by Progi1984** [comment]
@matks Travis is :red_circle:

**Comment by matks** [comment]
> @matks Travis is 🔴

Thanks for the notification 😉 I have checked and it looks like a bad failure from Travis
```
5.7: Pulling from library/mysql
latest: Pulling from prestashop/prestashop
ysql_1_3332d9b18b11 ... 
$ bash -c 'while [[ "$(curl -s -o /dev/null -w %{http_code} http://localhost:8001/index.php)" != "200" ]]; do sleep 5; done'
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
```

I restart the job. Next time you see Travis being red, can you check quickly whether the issue comes from the PR or from Travis ? 😉 that would be awesome (and very kind ❤️ ) and most importantly this will speed things because if you see the issue comes from Travis you can restart the job immediately (thanks to your maintainer rights) allowing the PR to go forward into the process 💪

**Comment by Progi1984** [comment]
@matks I restarted it 3 times ;)

**Comment by matks** [comment]
> @matks I restarted it 3 times ;)

You did not push string enough.

SMASH THAT THING

**Comment by Progi1984** [comment]
I emptied my Travis credit for this repository ;)

**Comment by matks** [comment]
I will redo it

**Pull request closed without merging**
