### PR TITLE
Update quick access link for orders

### PR DESCRIPTION
**Pull request by okom3pom**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Update quick access link for orders
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/27513
| How to test?      | Check if the link is good.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

### CODE REVIEW

**Review by matks — COMMENTED** [review]
What happens if a user has installed a module that replaces the Order page, and has modified the value of the SQL table to use the module page instead?

Maybe we need to verify that the link, before upgrade, targets the previous order page

**Comment by okom3pom** [comment]
Hello @matks 

I am not sure I understand.
There is a link and a name.
I did the same as for the other pages. But maybe we need to do more?

https://github.com/PrestaShop/autoupgrade/blob/dev/upgrade/sql/1.7.5.1.sql#L14-L17

**Comment by matks** [comment]
My bad I read again the PR and I think I was tired when I reviewed

**Review by matks — APPROVED** [review]

**Review by PierreRambaud — DISMISSED** [review]

**Comment by florine2623** [comment]
Hello @okom3pom ,

On my end I can't see the right link.

Here are the steps I did :
- Install PS 1.7.7.5
- Make sure autoupgrade is installed
- Install this PR
- Upgrade to PS 1.7.8.3
- Go to Manage your quick access -> old link is displayed :
Screenshot 2022-02-11 at 12 45 22

Am I missing something ?
Thanks!

**Comment by kpodemski** [comment]
Hello @okom3pom - rebase needed 👍

**Comment by okom3pom** [comment]
Rebase ok

**Review by saulaski — APPROVED** [review]

**Review by atomiix — APPROVED** [review]

**Review by florine2623 — CHANGES_REQUESTED** [review]
Hello @okom3pom ,

There are some conflicts in your PR, could you resolve them please ?
Thanks!

**Review by jolelievre — APPROVED** [review]
Thanks @okom3pom

**Review by jolelievre — DISMISSED** [review]
Ah my bad @okom3pom you indeed need to rebase your PR because it has conflicts

**Comment by okom3pom** [comment]
Ok

**Review by atomiix — APPROVED** [review]

**Comment by okom3pom** [comment]
Friendly remember @atomiix @kpodemski && @jolelievre 

When I see the current PR I will have to rebase again :)

**Review by atomiix — APPROVED** [review]

**Review by AureRita — APPROVED** [review]
Hi @okom3pom 

Thank you for your PR, I tested it and it works, as we can see here :

https://user-images.githubusercontent.com/100699445/182116165-c43f635c-d437-40e2-9087-70db25c21771.mp4

**Comment by okom3pom** [comment]
@AureRita QA ok ?

**Comment by AureRita** [comment]
@okom3pom  yes, Indeed, I thought we have to wait about the two other reviewers (like florine) so she'll put the last QA Approved, so yes QA approved

**Review by matthieu-rolland — COMMENTED** [review]
Thank you @okom3pom  and @AureRita 👍

**Pull request merged**
