### PR TITLE
Get all langs to generate data when filling ps_product_attribute_lang

### PR DESCRIPTION
**Pull request by Hlavtox**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | I forgot to use false param when calling Language::getLanguages(). Without it, it only returns active langs.
| Type?             | bug fix
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #https://github.com/PrestaShop/PrestaShop/issues/31466
| Sponsor company   | 
| How to test?      |

### CODE REVIEW

**Comment by Hlavtox** [comment]
Ping @kpodemski can we merge it without QA?

**Comment by Hlavtox** [comment]
@jf-viguier Pointed me to a much easier solution, I guess I will simplify it? And we don't need an extra PHP file for this step.

```sql
INSERT INTO ps_product_attribute_lang 
(id_product_attribute, id_lang, available_now, available_later)
SELECT ps_product_attribute.id_product_attribute, ps_lang.id_lang, '', ''
FROM ps_product_attribute CROSS JOIN ps_lang;
```

**Comment by kpodemski** [comment]
@Hlavtox looks legit!

**Comment by Hlavtox** [comment]
@kpodemski Ready to go

**Review by kpodemski — APPROVED** [review]

**Review by matthieu-rolland — APPROVED** [review]

**Comment by paulnoelcholot** [comment]
Hello @Hlavtox,

I add the label Blocked because the issue has not yet been verified by QA. As soon as this has been done, we will start testing on this PR.

**Comment by Hlavtox** [comment]
@paulnoelcholot I did the feature, I did the upgrade script and I know what is wrong with it. To every developer, it's completely clear that @jf-viguier is right. Please.

**Comment by kpodemski** [comment]
@paulnoelcholot I validated the issue

**Review by sallemiines — COMMENTED** [review]
Hello @Hlavtox 

Thanks for the PR ! it's LGTM !QA :heavy_check_mark: 


image



Thank you ! :rocket:

**Comment by Hlavtox** [comment]
@sallemiines Thank you!!!!

**Pull request merged**
