### PR TITLE
Check last version module

### PR DESCRIPTION
**Pull request by okom3pom**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Check last version of the module
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes https://github.com/PrestaShop/PrestaShop/issues/15194 and https://github.com/PrestaShop/PrestaShop/issues/26066
| How to test?      | You need to change the version number to see if the message is displayed correctly.
| Possible impacts? | Please indicate what parts of the software we need to check to make sure everything is alright.

### CODE REVIEW

**Review by Progi1984 — APPROVED** [review]

**Review by PierreRambaud — APPROVED** [review]

**Comment by florine2623** [comment]
Hello @okom3pom ,

Thanks for the PR !

With the PR installed, when the module is up-to-date ✅ :
Screenshot 2022-02-11 at 15 29 32

When the module is NOT up-to-date ⛔ :
Screenshot 2022-02-11 at 15 27 52

But in the [issue](https://github.com/PrestaShop/PrestaShop/issues/15194) and the [mockup](https://www.figma.com/file/GpRsUUCHcdhJPAaz7Eqzes/Autoupgrade?node-id=497%3A11710), it should not be displayed like this. We should have an alert like the following :
Screenshot 2022-02-11 at 15 30 28

Could you check it please ?
Thanks!

**Comment by okom3pom** [comment]
This is normal because it is for a new version

I gave the informations in the how to test

**Comment by okom3pom** [comment]
Hello @florine2623 

You don't need to test an out-of-date version, here is the procedure: 

https://www.okom3pom.com/videos/auto-upgrade-version-warning.webm

I use the version number 4.1.12 because the prestashop api is not up to date a dev can confirm it

**Comment by florine2623** [comment]
Hello @okom3pom ,

Thanks for the details ^^

I must have had some conflict in my test-shop.
I've made another installation from scratch. Now it works well ! The alert is displayed correctly !

It is QA ✅ !

**Comment by Progi1984** [comment]
Thanks @okom3pom & @florine2623

**Pull request merged**
