### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by ps-jarvis**

### CODE REVIEW

**Comment by ps-jarvis** [comment]
Hello @ps-jarvis!

This is your first pull request on the PrestaShop project. Thank you, and welcome to this Open Source community!

**Comment by Quetzacoalt91** [comment]
> Hello @ps-jarvis!
> 
> This is your first pull request on the PrestaShop project. Thank you, and welcome to this Open Source community!

image

**Comment by Hlavtox** [comment]
I must be dreaming, finally. :D 

@Quetzacoalt91 do you think you could set this up for all native modules?

**Comment by Quetzacoalt91** [comment]
We created a new Crowdin project for the native modules that could benefit the integrated translations. So yes, this is something we can do in the future once the solution is fully implemented here.

**Comment by Hlavtox** [comment]
@Quetzacoalt91 It would be good if it was in the current project, in `Modules` folder, so all people don't have to be reassigned to the new repository.

> native modules that could benefit the integrated translations

All native modules are using the new translation system, so the only thing that is blocking is the communication betweeen crowding and github. 👍

**Comment by Quetzacoalt91** [comment]
As far as know the current integration with Github does not allow other projects to be added in a specific subfolder, the result would have displayed autoupgrade among the existing folders.
At the moment it seems safer to create a new project (https://crowdin.com/project/prestashop-official-modules) where Crowdin add each reapository at the root.

**Pull request closed without merging**
