### PR TITLE
Adding the PATCH method to the REST API (webservices)

### PR DESCRIPTION
**Pull request by nsorosac**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Need this SQL upgrade for this PR: https://github.com/PrestaShop/PrestaShop/pull/27952
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | https://github.com/PrestaShop/PrestaShop/issues/28748
| How to test?      | See https://github.com/PrestaShop/PrestaShop/pull/27952
| Possible impacts? | None

### CODE REVIEW

**Review by matks — APPROVED** [review]
PR is valid. To be tested with initial PR 👍  thank you @nsorosac

**Review by Progi1984 — APPROVED** [review]

**Review by PrestaEdit — APPROVED** [review]

**Comment by PrestaEdit** [comment]
Now that the PR is merged, does not forgot this one.

**Review by matthieu-rolland — APPROVED** [review]

**Review by jolelievre — APPROVED** [review]
Thanks @nsorosac

**Review by khouloudbelguith — COMMENTED** [review]
Hi @nsorosac,

I followed these steps:

1. Install PS1752 with English language & France country
2. Upgrade to 8.0.x using this PR
3. Go to BO > Catalog > Files > Add a new file with type jpeg for example
4. Go to BO > Advanced Parameters > Webservice page & select Patch for the attachment
5. Using postman, I tried to update the attachment with the `Patch` method

image
But the file is not updated

I tried to update the attached with `PUT` method => OK
image


I attached a screen record

https://user-images.githubusercontent.com/16067358/173408235-586e989d-3fa5-4ac0-87b4-8456cc030f34.mp4

Thanks!

**Comment by nsorosac** [comment]
Hi @khouloudbelguith 

This problem seems related to the Core PR I made last month: https://github.com/PrestaShop/PrestaShop/pull/27952
It is not related to the autouprade module.

**Comment by khouloudbelguith** [comment]
Hi @nsorosac,

Thanks for your feedback.
I found another problem following these steps:
1. Install PS1752 with English language & France country
2. Upgrade to 8.0.x using this PR
3. Enable webservice & enable the Patch method 
image
4. I used postman to edit the image of a product 
image

=> See error: This method is not allowed

@nsorosac, is this issue related to this PR?
Ping @PrestaShop/prestashop-maintainers, Can I test this PR to 8.0.x or I should test this PR to make an upgrade to the new PR: https://github.com/PrestaShop/PrestaShop/pull/28747

Thanks!

**Review by khouloudbelguith — COMMENTED** [review]
Hi @nsorosac,

Thanks for your feedback.
I found another problem following these steps:
1. Install PS1752 with English language & France country
2. Upgrade to 8.0.x using this PR
3. Enable webservice & enable the Patch method 
image
4. I used postman to edit the image of a product 
image

=> See error: This method is not allowed

@nsorosac, is this issue related to this PR?
Ping @PrestaShop/prestashop-maintainers, Can I test this PR to 8.0.x or I should test this PR to make an upgrade to the new PR: https://github.com/PrestaShop/PrestaShop/pull/28747

Thanks!

**Comment by jolelievre** [comment]
Hi @nsorosac and @khouloudbelguith 

I took the liberty to rebase the PR to avoid losing some time.

@khouloudbelguith it should be testable now.

**Review by khouloudbelguith — COMMENTED** [review]
Hi @nsorosac,

I manage the same issue reported by @hibatallahAouadni in this [comment](https://github.com/PrestaShop/PrestaShop/pull/28747#issuecomment-1182203278) after an upgrade from PS1778 to this PR:https://github.com/PrestaShop/PrestaShop/pull/28747: the filename is changed
I attached a screen record

https://user-images.githubusercontent.com/16067358/179976146-449e7166-534a-4b91-946a-c40f2b9a5b68.mp4

I also tried to patch an image => NOK

image

It is the same issue reported [here](https://github.com/PrestaShop/autoupgrade/pull/479#pullrequestreview-1005934766)


Thanks!

**Comment by matks** [comment]
Now that https://github.com/PrestaShop/PrestaShop/pull/29638 is merged I think this PR can be tested again

**Review by khouloudbelguith — APPROVED** [review]
Hi @nsorosac,

It is ok :heavy_check_mark: 
I checked an upgrade from PS1.7.7.8 & from PS1.7.8.7 to 8.0.x
I checked those HTTP requests

- PATCH a file
- PATCH a category
- PATCH a product
- PATCH a brand
- PATCH a supplier
- PATCH a carrier
- PATCH a cart rule
- PATCH an order
- POST a product / PUT a product
- PUT a file

https://watch.screencastify.com/v/lKsPJYtLzuR3UBojfgom

https://watch.screencastify.com/v/XfLXj3xLcY644jIjbryR

Thanks!

**Comment by matks** [comment]
Thank you @khouloudbelguith

**Pull request merged**
